export const DEFAULT_SCHEMES = [

    {
      titleKey: "schemeTitlePmkisan",
      categoryKey: "schemeCategoryFinancial",
      benefitKey: "schemeBenefitPmkisan",
      eligibilityKey: "schemeEligibilityPmkisan",
      documentsKey: "schemeDocumentsPmkisan",
      icon: "💰",
      applyUrl: "https://pmkisan.gov.in/RegistrationFormupdated.aspx",
      applyLabel: "Apply on PM-KISAN",
      applicationNote: "Use the official new farmer registration form.",
      registrationSteps: [
        "Check that you meet the scheme rules and have your land records ready.",
        "Open New Farmer Registration, enter your Aadhaar number, mobile number and state, then complete Aadhaar authentication.",
        "Complete the form and submit it for verification by your State or Union Territory. Keep the registration reference.",
        "Check your application status and complete the required eKYC to receive installments.",
      ],
    },
    {
      titleKey: "schemeTitleInsurance",
      categoryKey: "schemeCategoryInsurance",
      benefitKey: "schemeBenefitInsurance",
      eligibilityKey: "schemeEligibilityInsurance",
      documentsKey: "schemeDocumentsInsurance",
      icon: "🛡️",
      applyUrl: "https://pmfby.gov.in/farmerRegistrationForm",
      applyLabel: "Apply for crop insurance",
      applicationNote: "Check notified crops, area and enrollment dates before applying.",
      registrationSteps: [
        "Check the current season's notified crops, area and enrollment deadline for your location.",
        "Create or sign in to your farmer account on the official PMFBY portal.",
        "Choose the season, state, district, crop and insured area, then enter your bank details.",
        "Upload the requested identity, bank and land or cultivation documents, pay the displayed premium and save the receipt.",
      ],
    },
    {
      titleKey: "schemeTitleCredit",
      categoryKey: "schemeCategoryLoan",
      benefitKey: "schemeBenefitCredit",
      eligibilityKey: "schemeEligibilityCredit",
      documentsKey: "schemeDocumentsCredit",
      icon: "🏦",
      applyUrl: "https://pmkisan.gov.in/Documents/Kcc.pdf",
      applyLabel: "Get KCC application form",
      applicationNote: "Submit the completed form to a participating bank.",
      registrationSteps: [
        "Download and complete the KCC application form, including your crop and credit requirements.",
        "Take the form and requested identity, address, land or cultivation, and bank documents to a participating bank or cooperative institution.",
        "The bank reviews your eligibility and application. Respond to any request for additional information.",
        "If approved, review the sanctioned limit, repayment terms and card instructions with the bank before using the credit.",
      ],
    },
    {
      titleKey: "schemeTitleSoil",
      categoryKey: "schemeCategorySoil",
      benefitKey: "schemeBenefitSoil",
      eligibilityKey: "schemeEligibilityAllFarmers",
      documentsKey: "schemeDocumentsSoil",
      icon: "🌱",
      applyUrl: "https://soilhealth.dac.gov.in/soilhealthcard",
      applyLabel: "Get Soil Health Card",
      applicationNote: "Use the official portal to access Soil Health Card services.",
      registrationSteps: [
        "Contact your District Agriculture Office or the nearest soil testing laboratory and ask to register your farm for soil testing.",
        "Share your farmer and field details with the agriculture staff or authorized soil-sampling worker.",
        "Arrange a field visit so a trained worker can collect and label a soil sample for testing.",
        "Use the Soil Health Card portal to track the sample and view or download the card when the test is complete.",
      ],
    },
    {
      titleKey: "schemeTitleIrrigation",
      categoryKey: "schemeCategoryIrrigation",
      benefitKey: "schemeBenefitIrrigation",
      eligibilityKey: "schemeEligibilityIrrigation",
      documentsKey: "schemeDocumentsCredit",
      icon: "💧",
      applyUrl: "https://pmksy.gov.in/Default.aspx",
      applyLabel: "Official scheme information",
      applicationNote: "For assistance or applications, contact your state agriculture or horticulture department.",
      registrationSteps: [
        "Ask your State Agriculture or Horticulture Department which irrigation support component is open in your district.",
        "Confirm local eligibility, application dates, approved equipment and the subsidy rules for your state.",
        "Submit the state application with the documents requested, such as identity, bank, landholding and irrigation-site details.",
        "Wait for the department's review or field inspection and written approval before purchasing or installing equipment.",
      ],
    },
    {
      titleKey: "schemeTitleEnam",
      categoryKey: "schemeCategoryMarket",
      benefitKey: "schemeBenefitEnam",
      eligibilityKey: "schemeEligibilityEnam",
      documentsKey: "schemeDocumentsEnam",
      icon: "📈",
      applyUrl: "https://enam.gov.in/registration",
      applyLabel: "Register on e-NAM",
      applicationNote: "Farmer registration is completed through the official e-NAM portal.",
      registrationSteps: [
        "Open the e-NAM registration form, choose Farmer as the registration type, and select your State and APMC mandi.",
        "Enter your personal and contact details. Use an email address you can access for registration messages and login details.",
        "Sign in with the temporary credentials and complete the farmer and bank details requested for APMC registration.",
        "Submit the details for APMC review. Check your application status and use the permanent login after approval.",
      ],
    },
];
