const LANGUAGE_STORAGE_KEY = "agrisathi-language";
export const LANGUAGE_CHANGE_EVENT = "agrisathi-language-changed";

export const DEFAULT_LANGUAGE = "en";

export const languages = [
  {
    code: "en",
    name: "English",
    nativeName: "English",
    locale: "en-IN",
    direction: "ltr",
  },
  {
    code: "te",
    name: "Telugu",
    nativeName: "తెలుగు",
    locale: "te-IN",
    direction: "ltr",
  },
  {
    code: "hi",
    name: "Hindi",
    nativeName: "हिन्दी",
    locale: "hi-IN",
    direction: "ltr",
  },
];

export const translations = {
  en: {
    productLoading: "Loading product",
    productUnavailable: "Product unavailable",
    viewOtherProducts: "View Other Products",
    productInformation: "Product Information",
    dealerLabel: "🏪 Dealer",
    selectQuantity: "Select Quantity",
    totalLabel: "Total:",
    sendingOrderRequest: "Sending Request...",
    paymentCashOnDelivery: "Payment: Cash on Delivery",
    categorySeeds: "Seeds",
    categoryFertilizer: "Fertilizer",
    categoryPesticide: "Pesticide",
    categoryTools: "Tools",
    categoryFeed: "Feed",
    categoryAll: "All",
    noProductsFound: "No products found",
    tryDifferentProduct: "Try another product name or category.",
    noDealerProducts: "Nearby dealers have not added available products yet.",
    clearSearch: "Clear Search",
    refreshProducts: "Refresh Products",
    noProductImage: "No product image",
    lowStock: "Low stock",
    inStock: "In stock",
    priceLabel: "Price",
    perUnit: "per {{unit}}",
    availableLabel: "Available",
    unitsLabel: "units",
    locationNotAvailable: "Location not available",
    callDealer: "📞 Call Dealer",
    approvedDealer: "✓ Approved Dealer",
    viewProductDetails: "👁️ View Product Details",
    sendingOrder: "Sending...",
    requestOrder: "Request Order",
    decreaseQuantity: "Decrease quantity",
    increaseQuantity: "Increase quantity",
    nearbyProductsLoading: "Finding nearby products",
    pleaseWait: "Please wait...",
    localMarketplace: "🏪 Local Marketplace",
    marketplaceIntro: "Seeds, fertilizers and farm products.",
    myOrdersButton: "🛒 My Orders",
    nearLabel: "📍 Near",
    registeredArea: "your registered area",
    searchProduct: "🔍 Search product",
    marketplaceSearchPlaceholder: "Urea, cotton seed, pesticide...",
    speak: "🎤 Speak",
    voiceSearchLabel: "Voice search:",
    nearbyProducts: "Nearby Products",
    productsFound: "found",
    orderRequestSent: "Order request sent. Check My Orders for the dealer response.",
    orderAccessBlocked: "Order access is blocked by Firebase rules.",
    orderRequestFailed: "Order request could not be sent.",
    marketLoading: "Loading market prices",
    detectingMarketArea: "Detecting your market area",
    localCropPricesTitle: "📈 Local Crop Prices",
    marketPageIntro: "Government mandi prices with crop images for easy farmer understanding.",
    savedFarmerLocation: "Saved farmer location",
    cropCount: "Crops",
    marketCount: "Markets",
    priceRecords: "Price Records",
    averagePrice: "Average Price",
    yourMainCrop: "Your main crop",
    showPrices: "Show Prices",
    searchAnyCrop: "🔍 Search any crop",
    cropSearchPlaceholder: "Cotton, paddy, tomato, maize...",
    allDistricts: "All Districts",
    allMarkets: "All Markets",
    latestRecords: "Latest Records",
    highestPrice: "Highest Price",
    lowestPrice: "Lowest Price",
    marketSummaryTitle: "Market Price Summary",
    bestPrice: "Best Price",
    averageLabel: "Average",
    bestPlace: "Best Place",
    viewCommodityDetails: "View {{crop}} Details",
    mandiPriceDetails: "Mandi Price Details",
    refreshing: "Refreshing...",
    noMarketRecords: "No market records available.",
    minPrice: "Min",
    modalPrice: "Modal",
    maxPrice: "Max",
    dateLabel: "Date:",
    notAvailable: "Not available",
    openMarket: "Open Market",
    nearbySellingPlaces: "Nearby Selling Places",
    searchInMaps: "Search in Maps",
    searchingNearbyPlaces: "Searching nearby selling places...",
    noMappedPlaces: "Nearby mapped selling places were not found.",
    addressNotAvailable: "Address not available",
    distanceLabel: "Distance:",
    directions: "Directions",
    call: "Call",
    categoryAllCrops: "All Crops",
    categoryGrains: "Grains",
    categoryPulses: "Pulses",
    categoryVegetables: "Vegetables",
    categoryFruits: "Fruits",
    categorySpices: "Spices",
    categoryOilseeds: "Oilseeds",
    categoryFibre: "Fibre",
    cropNameSort: "Crop Name",
    cropPriceSummary: "Crop Price Summary",
    loadingPrices: "Loading prices...",
    noCropPricesForFilters: "No crop prices found for the selected filters.",
    recordCount: "records",
    marketCountLower: "markets",
    highest: "Highest",
    lowest: "Lowest",
    checkBeforeSelling: "Check before selling",
    marketInfoUnavailable: "Market information could not be loaded.",
    locationFallback: "Location is unavailable. Showing prices from your saved profile.",
    exactLocationFallback: "Exact location could not be identified. Showing prices from your saved profile.",
    locationPermissionNearby: "Allow location access to find nearby markets. Saved profile location is being used.",
    noCurrentMandiPrices: "No current government mandi prices were found for this location.",
    govtPricesUnavailable: "Government mandi prices could not be loaded.",
    locationRequiredSelling: "Location is required to search nearby selling points.",
    noMappedSellingPoints: "No mapped selling points were found nearby. Use the map search option.",
    nearbySellingUnavailable: "Nearby selling points are temporarily unavailable. You can still search through maps.",
    sellingTypeMarket: "Market",
    sellingTypeRiceMill: "Rice Mill",
    sellingTypeOilMill: "Oil Mill",
    sellingTypeCottonMill: "Cotton Mill",
    sellingTypeDalMill: "Dal Mill",
    sellingTypeFlourMill: "Flour Mill",
    sellingTypeMarketplace: "Marketplace",
    cropPriceSummaryUnavailable: "Price unavailable",
    goodMarketPrice: "Good market price",
    compareMarkets: "Compare markets",
    forgotPasswordTitle: "Forgot Password?",
    forgotPasswordIntro: "Enter your registered email address and we will send you a password reset link.",
    registeredEmail: "Registered Email",
    enterEmail: "Enter your email",
    sendResetLink: "Send Reset Link",
    sendingResetLink: "Sending Reset Link...",
    resetEmailRequired: "Please enter your email address.",
    resetEmailInvalid: "Please enter a valid email address.",
    resetEmailSent: "If an account exists with this email, a password reset link has been sent. Please check your inbox and spam folder.",
    backToLogin: "← Back to Login",
    checkYourEmail: "📧 Check your email",
    resetEmailDelay: "The password reset link may take a few minutes to arrive. Also check your spam or junk folder.",
    governmentSchemesTitle: "🏛️ Government Schemes",
    schemeTitlePmkisan: "PM Kisan Samman Nidhi",
    schemeTitleInsurance: "Pradhan Mantri Fasal Bima Yojana",
    schemeTitleCredit: "Kisan Credit Card",
    schemeTitleSoil: "Soil Health Card Scheme",
    schemeTitleIrrigation: "PM Krishi Sinchayee Yojana",
    schemeTitleEnam: "eNAM",
    governmentSchemesIntro: "Find useful government schemes for farmers.",
    searchSchemesPlaceholder: "Search scheme, insurance, loan, irrigation...",
    schemeBenefitLabel: "Benefit:",
    schemeEligibilityLabel: "Eligibility:",
    schemeDocumentsLabel: "Documents:",
    speakScheme: "🔊 Speak",
    applyInfo: "Apply Info",
    schemeApplySoon: "Application information will be available soon.",
    noSchemesFound: "No schemes found",
    searchSchemesHint: "Try searching with loan, insurance, irrigation, market or soil.",
    schemeCategoryFinancial: "Financial Support",
    schemeCategoryInsurance: "Crop Insurance",
    schemeCategoryLoan: "Loan Support",
    schemeCategorySoil: "Soil Testing",
    schemeCategoryIrrigation: "Irrigation",
    schemeCategoryMarket: "Market Support",
    schemeBenefitPmkisan: "₹6000 yearly support for eligible farmers.",
    schemeEligibilityPmkisan: "Small and marginal farmers with valid land records.",
    schemeDocumentsPmkisan: "Aadhaar, bank account, land details.",
    schemeBenefitInsurance: "Crop loss protection due to natural calamities.",
    schemeEligibilityInsurance: "Farmers growing notified crops in notified areas.",
    schemeDocumentsInsurance: "Aadhaar, bank account, crop details, land details.",
    schemeBenefitCredit: "Short-term crop loan at lower interest.",
    schemeEligibilityCredit: "Farmers, tenant farmers, sharecroppers.",
    schemeDocumentsCredit: "Aadhaar, land records, bank details.",
    schemeBenefitSoil: "Soil nutrient report and fertilizer advice.",
    schemeEligibilityAllFarmers: "All farmers.",
    schemeDocumentsSoil: "Farmer details and land details.",
    schemeBenefitIrrigation: "Support for better irrigation and water usage.",
    schemeEligibilityIrrigation: "Farmers needing irrigation improvement.",
    schemeBenefitEnam: "Online agricultural market platform.",
    schemeEligibilityEnam: "Farmers selling produce in registered markets.",
    schemeDocumentsEnam: "Farmer ID, bank account, produce details.",
    cropDiseasePageTitle: "🌿 Crop Disease Detection",
    cropDiseasePageIntro: "Take or upload a crop photo for AI-based guidance.",
    cropNameOptional: "Crop name (optional)",
    cropNameExample: "Example: Cotton, rice",
    cropOrLeafPhoto: "Crop or leaf photo",
    imageAutoEnhancement: "The app will automatically improve brightness, contrast and clarity when possible.",
    processingPhoto: "Processing photo...",
    detectDiseaseButton: "🔍 Detect Disease",
    detectedCrop: "Detected crop",
    possibleCondition: "Possible condition",
    visibleSymptoms: "Visible symptoms",
    likelyCauses: "Likely causes",
    immediateActions: "Immediate actions",
    recommendedPesticide: "Recommended pesticide",
    availablePesticides: "Available pesticide products",
    recommendedFertilizer: "Recommended fertilizer",
    availableFertilizers: "Available fertilizer products",
    treatmentGuidance: "Treatment guidance",
    prevention: "Prevention",
    imageRequired: "Upload a photo of the affected leaf or plant first.",
    photoNotClearPlant: "A crop or plant was not clearly detected. Please take another photo showing the affected leaf or plant.",
    imageImproveTimeout: "Image improvement took too long. Please try again.",
    diseaseDetectionFailed: "Disease detection failed. Please try another photo.",
    weatherLoading: "Loading weather",
    detectingLocation: "Detecting your location",
    dashboardLink: "← Dashboard",
    farmWeather: "🌦️ Farm Weather",
    localForecastAdvice: "Local forecast and farming advice.",
    detecting: "Detecting...",
    refreshLocation: "📍 Refresh Location",
    locationNotDetected: "Location not detected",
    locationPermissionNeeded: "Location permission needed",
    enableLocationWeather: "Enable location to receive local weather and farm advice.",
    detectMyLocation: "Detect My Location",
    currentTemperature: "Current temperature",
    feelsLike: "Feels like",
    rainLabel: "🌧️ Rain",
    windLabel: "💨 Wind",
    windGustLabel: "💨 Wind Gust",
    weatherWarnings: "⚠️ Weather Warnings",
    todaysFarmAdvice: "🌾 Today’s Farm Advice",
    pesticideLabelInstructions: "Follow the pesticide label and local agriculture officer’s instructions.",
    next12Hours: "🕒 Next 12 Hours",
    forecast7Day: "📅 7-Day Forecast",
    rainChance: "🌧️ Rain chance:",
    cropSuggestions: "🌱 Crop Suggestions",
    cropSuggestionsBasis: "Based on season, saved soil type and available market-price data.",
    seasonLabel: "season",
    matchesSavedSoil: "Matches saved soil type",
    suitableCurrentSeason: "Suitable for the current season",
    marketPriceLabel: "Market:",
    marketPriceUnavailable: "Market-price data is not available yet. Suggestions currently use season and soil type.",
    cropSelectionFactors: "Crop selection also depends on water, seed availability, local pests, costs and official agricultural advice.",
    cropHelp: "Crop Help",
    farmProfile: "Farm Profile",
    conditionClearSky: "Clear Sky",
    conditionMostlyClear: "Mostly Clear",
    conditionPartlyCloudy: "Partly Cloudy",
    conditionCloudy: "Cloudy",
    conditionFog: "Fog",
    conditionLightDrizzle: "Light Drizzle",
    conditionDrizzle: "Drizzle",
    conditionHeavyDrizzle: "Heavy Drizzle",
    conditionLightRain: "Light Rain",
    conditionRain: "Rain",
    conditionHeavyRain: "Heavy Rain",
    conditionRainShowers: "Rain Showers",
    conditionHeavyShowers: "Heavy Showers",
    conditionThunderstorm: "Thunderstorm",
    conditionSevereThunderstorm: "Severe Thunderstorm",
    conditionWeather: "Weather",
    sprayAdviceUnavailable: "Spray advice unavailable",
    irrigationAdviceUnavailable: "Irrigation advice unavailable",
    fieldWorkAdviceUnavailable: "Field work advice unavailable",
    forecastRequiredSpray: "Weather forecast is required before planning pesticide spraying.",
    forecastRequiredIrrigation: "Weather forecast is required before irrigation planning.",
    refreshWeatherTryAgain: "Refresh weather data and try again.",
    avoidSpraying: "Avoid spraying now",
    rainWashSpray: "Rain may wash away the spray. Wait for a dry period.",
    windSprayDrift: "Wind is too strong and may cause spray drift.",
    unsuitableSprayTemperature: "Temperature is unsuitable for safe and effective spraying.",
    possibleSprayWindow: "Possible spray window",
    sprayWindowAdvice: "Weather appears suitable around {{time}}. Recheck the pesticide label before spraying.",
    waitBeforeSpraying: "Wait before spraying",
    noSprayWindow: "No reliable dry and low-wind period was found in the next 24 hours.",
    delayIrrigation: "Delay irrigation",
    rainLikelyCheckField: "Rain is likely soon. Check the field after rainfall before watering.",
    checkCropMoisture: "Check crop moisture",
    hotDryIrrigateSandy: "Hot and dry conditions may reduce moisture quickly. Irrigate early morning if the root zone is dry.",
    highWaterDemand: "Water demand may be high. Check soil moisture and irrigate early morning if needed.",
    avoidExcessWatering: "Avoid excess watering",
    soilMayHoldWater: "Your soil may hold water longer. Check moisture below the surface before irrigation.",
    checkSoilBeforeWatering: "Check soil before watering",
    noUrgentIrrigation: "Weather does not indicate urgent irrigation. Check root-zone moisture first.",
    postponeFieldWork: "Postpone major field work",
    windRainFieldWork: "Strong wind or rain may affect harvesting, fertilizer application and equipment work.",
    fieldWorkPossible: "Field work is possible",
    suitableContinueChecking: "Conditions appear suitable, but continue checking local sky conditions.",
    veryHighTemperatureWarning: "Very high temperature: avoid midday spraying and protect workers and livestock.",
    strongWindWarning: "Strong wind: secure light materials and avoid spraying.",
    rainAtLocationWarning: "Rain is occurring at the detected location.",
    highRainTodayWarning: "High rain chance today: protect harvested produce and stored inputs.",
    weatherLoadFailed: "Weather information could not be loaded.",
    locationUnsupported: "Location detection is not supported on this device.",
    localWeatherFailed: "Weather could not be loaded for your location.",
    locationAccessNeeded: "Allow location access to receive local weather and farming advice.",
    currentLocation: "Current Location",
    seasonKharif: "Kharif",
    seasonRabi: "Rabi",
    seasonSummer: "Summer",
    rainValueLabel: "💧 Rain:",
    windValueLabel: "💨 Wind:",
    roleSelectionTitle: "Choose how you’ll use AgriSaathi",
    roleSelectionSubtitle: "Your smart companion for agriculture",
    selectRoleToContinue: "Select your role to continue",
    roleFarmer: "Farmer",
    roleFarmerDescription: "Access crop information, disease detection, weather, market prices and local agricultural products.",
    roleDealer: "Dealer",
    roleDealerDescription: "Manage products, stock, farmer orders and sales.",
    roleAdmin: "Admin",
    roleAdminDescription: "Manage farmers, dealers, products, reports, approvals and system activities.",
    continueAsRole: "Continue as {{role}}",
    openingLogin: "Opening login...",
    simpleToUse: "Simple to use",
    farmerFriendly: "Farmer friendly",
    secureAccess: "Secure access",
    selectLanguage: "Select Language",
    chooseLanguage: "Choose your preferred language",
    smartFarmingCompanion: "Smart Farming Companion",
    welcomeFarmer: "Welcome Farmer",
    chooseService: "Choose a service below",

    login: "Login",
    logout: "Logout",
    createAccount: "Create Account",
    email: "Email",
    password: "Password",
    dashboard: "Dashboard",

    home: "Home",
    orders: "Orders",
    notifications: "Notifications",
    community: "Community",
    profile: "Profile",
    settings: "Settings",

    weather: "Weather",
    cropDisease: "Crop Disease",
    marketPrices: "Market Prices",
    govtSchemes: "Government Schemes",
    farmerProfile: "Farmer Profile",
    dealerProducts: "Dealers",
    myOrders: "My Orders",
    voiceAssistant: "Voice Assistant",

    scanCrop: "Scan Crop",
    localDealers: "Local Dealers",
    buyProducts: "Buy Products",
    checkMandi: "Check Mandi Prices",
    trackPurchase: "Track Purchase",
    farmingServices: "Farming Services",

    back: "Back",
    refresh: "Refresh",
    loading: "Loading...",
    save: "Save",
    cancel: "Cancel",
    continue: "Continue",
    retry: "Try Again",

    languageChanged: "Language changed successfully.",
    noInformation: "Information is not available.",
    openingAgriSaathi: "Opening AgriSaathi...",
    latestOrder: "Latest Order",
    farmProduct: "Farm product",
    quantity: "Quantity",
    trackOrder: "Track Order",
    schemes: "Schemes",
    nearbyServices: "Nearby Services",
    nearbyServicesDescription: "Find agriculture offices, soil-testing labs, equipment services and other farming support nearby.",
    openNearbyServices: "Open Nearby Services",
    voice: "Voice",
    waitingForDealer: "Waiting for dealer",
    dealerAccepted: "Dealer accepted",
    orderRejected: "Order rejected",
    markedDelivered: "Marked delivered",
    deliveryConfirmed: "Delivery confirmed",
    paymentConfirmed: "Payment confirmed",
    completed: "Completed",
    cancelled: "Cancelled",
    orderUpdate: "Order update",
    appLanguage: "App Language",
    changeLanguageAnytime: "Change the whole Farmer Module language anytime.",
    languageUpdated: "Application language changed.",
    myProfile: "My Profile",
    personalFarmInformation: "Personal and farm information.",    goodMorning: "Good Morning",
    goodAfternoon: "Good Afternoon",
    goodEvening: "Good Evening",
    farmer: "Farmer",
    farmLocationNotAdded: "Farm location not added",
    openNotifications: "Open notifications",
    loadingLocalWeather: "Loading local weather...",
    currentWeather: "Current weather",
    humidity: "Humidity",
    weatherUnavailable: "Weather unavailable",
    allowLocationForWeather: "Allow location access for local farm weather.",
    openVoiceAssistant: "Open AgriSaathi voice assistant",
    askAgriSaathi: "Ask AgriSaathi",
    speakInYourLanguage: "Tap the microphone and speak in your language.",
    startSpeaking: "Start Speaking",
    checkDisease: "Check disease",
    prices: "Prices",
    whatDoYouNeed: "What do you need?",
    loadingMarketPrice: "Loading crop market price...",
    marketPrice: "Market Price",
    cropPrices: "Crop prices",
    noCurrentMarketRecord: "No current price record was found. Open the market page to view all crops and mandis.",
    viewMarketPrices: "View market prices",
    localMarketPrice: "Local Market Price",
    localMandi: "Local mandi",
    nearbyMarket: "Nearby market",
    perQuintal: "per quintal",
    minimum: "Minimum",
    maximum: "Maximum",
    compareAllMarkets: "Compare All Markets",

  },

  te: {
    productLoading: "ఉత్పత్తి లోడ్ అవుతోంది",
    productUnavailable: "ఉత్పత్తి అందుబాటులో లేదు",
    viewOtherProducts: "ఇతర ఉత్పత్తులు చూడండి",
    productInformation: "ఉత్పత్తి సమాచారం",
    dealerLabel: "🏪 డీలర్",
    selectQuantity: "పరిమాణాన్ని ఎంచుకోండి",
    totalLabel: "మొత్తం:",
    sendingOrderRequest: "అభ్యర్థన పంపుతోంది...",
    paymentCashOnDelivery: "చెల్లింపు: వస్తువు అందినప్పుడు నగదు",
    categorySeeds: "విత్తనాలు",
    categoryFertilizer: "ఎరువులు",
    categoryPesticide: "పురుగుమందులు",
    categoryTools: "పరికరాలు",
    categoryFeed: "పశుగ్రాసం",
    categoryAll: "అన్నీ",
    noProductsFound: "ఉత్పత్తులు కనబడలేదు",
    tryDifferentProduct: "మరో ఉత్పత్తి పేరు లేదా వర్గంతో వెతకండి.",
    noDealerProducts: "దగ్గరలోని డీలర్లు అందుబాటులో ఉన్న ఉత్పత్తులను ఇంకా జోడించలేదు.",
    clearSearch: "శోధనను తొలగించండి",
    refreshProducts: "ఉత్పత్తులను రిఫ్రెష్ చేయండి",
    noProductImage: "ఉత్పత్తి చిత్రం లేదు",
    lowStock: "నిల్వ తక్కువ",
    inStock: "నిల్వలో ఉంది",
    priceLabel: "ధర",
    perUnit: "ప్రతి {{unit}}కు",
    availableLabel: "అందుబాటులో ఉంది",
    unitsLabel: "యూనిట్లు",
    locationNotAvailable: "స్థానం అందుబాటులో లేదు",
    callDealer: "📞 డీలర్‌కు కాల్ చేయండి",
    approvedDealer: "✓ ఆమోదిత డీలర్",
    viewProductDetails: "👁️ ఉత్పత్తి వివరాలు చూడండి",
    sendingOrder: "పంపుతోంది...",
    requestOrder: "ఆర్డర్ అభ్యర్థించండి",
    decreaseQuantity: "పరిమాణం తగ్గించండి",
    increaseQuantity: "పరిమాణం పెంచండి",
    nearbyProductsLoading: "దగ్గరలోని ఉత్పత్తులను వెతుకుతోంది",
    pleaseWait: "దయచేసి వేచి ఉండండి...",
    localMarketplace: "🏪 స్థానిక మార్కెట్",
    marketplaceIntro: "విత్తనాలు, ఎరువులు మరియు వ్యవసాయ ఉత్పత్తులు.",
    myOrdersButton: "🛒 నా ఆర్డర్లు",
    nearLabel: "📍 దగ్గరలో",
    registeredArea: "మీ నమోదిత ప్రాంతం",
    searchProduct: "🔍 ఉత్పత్తిని వెతకండి",
    marketplaceSearchPlaceholder: "యూరియా, పత్తి విత్తనాలు, పురుగుమందు...",
    speak: "🎤 మాట్లాడండి",
    voiceSearchLabel: "వాయిస్ శోధన:",
    nearbyProducts: "దగ్గరలోని ఉత్పత్తులు",
    productsFound: "కనిపించాయి",
    orderRequestSent: "ఆర్డర్ అభ్యర్థన పంపించాం. డీలర్ స్పందన కోసం నా ఆర్డర్లు చూడండి.",
    orderAccessBlocked: "Firebase నియమాల వల్ల ఆర్డర్ ప్రాప్యత నిరోధించబడింది.",
    orderRequestFailed: "ఆర్డర్ అభ్యర్థన పంపలేకపోయాం.",
    marketLoading: "మార్కెట్ ధరలు లోడ్ అవుతున్నాయి",
    detectingMarketArea: "మీ మార్కెట్ ప్రాంతాన్ని గుర్తిస్తోంది",
    localCropPricesTitle: "📈 స్థానిక పంట ధరలు",
    marketPageIntro: "రైతులు సులభంగా అర్థం చేసుకునేందుకు పంట చిత్రాలతో ప్రభుత్వ మండీ ధరలు.",
    savedFarmerLocation: "రైతు సేవ్ చేసిన స్థానం",
    cropCount: "పంటలు",
    marketCount: "మార్కెట్లు",
    priceRecords: "ధరల వివరాలు",
    averagePrice: "సగటు ధర",
    yourMainCrop: "మీ ప్రధాన పంట",
    showPrices: "ధరలు చూపించండి",
    searchAnyCrop: "🔍 ఏ పంటనైనా వెతకండి",
    cropSearchPlaceholder: "పత్తి, వరి, టమాటా, మొక్కజొన్న...",
    allDistricts: "అన్ని జిల్లాలు",
    allMarkets: "అన్ని మార్కెట్లు",
    latestRecords: "తాజా వివరాలు",
    highestPrice: "అత్యధిక ధర",
    lowestPrice: "అత్యల్ప ధర",
    marketSummaryTitle: "మార్కెట్ ధరల సారాంశం",
    bestPrice: "మంచి ధర",
    averageLabel: "సగటు",
    bestPlace: "మంచి మార్కెట్",
    viewCommodityDetails: "{{crop}} వివరాలు చూడండి",
    mandiPriceDetails: "మండీ ధరల వివరాలు",
    refreshing: "రిఫ్రెష్ అవుతోంది...",
    noMarketRecords: "మార్కెట్ ధరల వివరాలు అందుబాటులో లేవు.",
    minPrice: "కనిష్ఠం",
    modalPrice: "మధ్యస్థ ధర",
    maxPrice: "గరిష్ఠం",
    dateLabel: "తేదీ:",
    notAvailable: "అందుబాటులో లేదు",
    openMarket: "మార్కెట్ తెరవండి",
    nearbySellingPlaces: "దగ్గరలోని విక్రయ కేంద్రాలు",
    searchInMaps: "మ్యాప్స్‌లో వెతకండి",
    searchingNearbyPlaces: "దగ్గరలోని విక్రయ కేంద్రాలను వెతుకుతోంది...",
    noMappedPlaces: "మ్యాప్‌లో దగ్గరలోని విక్రయ కేంద్రాలు కనబడలేదు.",
    addressNotAvailable: "చిరునామా అందుబాటులో లేదు",
    distanceLabel: "దూరం:",
    directions: "దారి చూపించండి",
    call: "కాల్ చేయండి",
    categoryAllCrops: "అన్ని పంటలు",
    categoryGrains: "ధాన్యాలు",
    categoryPulses: "పప్పుధాన్యాలు",
    categoryVegetables: "కూరగాయలు",
    categoryFruits: "పండ్లు",
    categorySpices: "మసాలా దినుసులు",
    categoryOilseeds: "నూనెగింజలు",
    categoryFibre: "పీచు పంటలు",
    cropNameSort: "పంట పేరు",
    cropPriceSummary: "పంట ధరల సారాంశం",
    loadingPrices: "ధరలు లోడ్ అవుతున్నాయి...",
    noCropPricesForFilters: "ఎంచుకున్న ఫిల్టర్లకు పంట ధరలు కనబడలేదు.",
    recordCount: "వివరాలు",
    marketCountLower: "మార్కెట్లు",
    highest: "అత్యధికం",
    lowest: "అత్యల్పం",
    checkBeforeSelling: "విక్రయించే ముందు పరిశీలించండి",
    marketInfoUnavailable: "మార్కెట్ సమాచారం లోడ్ కాలేదు.",
    locationFallback: "స్థానం అందుబాటులో లేదు. సేవ్ చేసిన ప్రొఫైల్ స్థానం ధరలు చూపిస్తున్నాం.",
    exactLocationFallback: "ఖచ్చితమైన స్థానాన్ని గుర్తించలేకపోయాం. సేవ్ చేసిన ప్రొఫైల్ స్థానం ధరలు చూపిస్తున్నాం.",
    locationPermissionNearby: "దగ్గరలోని మార్కెట్లను కనుగొనడానికి స్థాన అనుమతిని ఇవ్వండి. సేవ్ చేసిన ప్రొఫైల్ స్థానాన్ని ఉపయోగిస్తున్నాం.",
    noCurrentMandiPrices: "ఈ స్థానానికి ప్రస్తుత ప్రభుత్వ మండీ ధరలు కనబడలేదు.",
    govtPricesUnavailable: "ప్రభుత్వ మండీ ధరలు లోడ్ కాలేదు.",
    locationRequiredSelling: "దగ్గరలోని విక్రయ కేంద్రాల కోసం స్థానం అవసరం.",
    noMappedSellingPoints: "దగ్గరలో మ్యాప్ చేసిన విక్రయ కేంద్రాలు కనబడలేదు. మ్యాప్‌లో వెతకండి.",
    nearbySellingUnavailable: "దగ్గరలోని విక్రయ కేంద్రాలు తాత్కాలికంగా అందుబాటులో లేవు. మ్యాప్స్‌లో వెతకవచ్చు.",
    sellingTypeMarket: "మార్కెట్",
    sellingTypeRiceMill: "రైస్ మిల్",
    sellingTypeOilMill: "ఆయిల్ మిల్",
    sellingTypeCottonMill: "కాటన్ మిల్",
    sellingTypeDalMill: "పప్పు మిల్",
    sellingTypeFlourMill: "పిండి మిల్",
    sellingTypeMarketplace: "మార్కెట్ స్థలం",
    cropPriceSummaryUnavailable: "ధర అందుబాటులో లేదు",
    goodMarketPrice: "మంచి మార్కెట్ ధర",
    compareMarkets: "మార్కెట్లను పోల్చండి",
    forgotPasswordTitle: "పాస్‌వర్డ్ మర్చిపోయారా?",
    forgotPasswordIntro: "మీ నమోదిత ఇమెయిల్ చిరునామాను నమోదు చేయండి. పాస్‌వర్డ్ రీసెట్ లింక్ పంపిస్తాము.",
    registeredEmail: "నమోదిత ఇమెయిల్",
    enterEmail: "మీ ఇమెయిల్ నమోదు చేయండి",
    sendResetLink: "రీసెట్ లింక్ పంపండి",
    sendingResetLink: "రీసెట్ లింక్ పంపుతోంది...",
    resetEmailRequired: "దయచేసి మీ ఇమెయిల్ చిరునామాను నమోదు చేయండి.",
    resetEmailInvalid: "దయచేసి సరైన ఇమెయిల్ చిరునామాను నమోదు చేయండి.",
    resetEmailSent: "ఈ ఇమెయిల్‌తో ఖాతా ఉంటే, పాస్‌వర్డ్ రీసెట్ లింక్ పంపించాం. మీ ఇన్‌బాక్స్ మరియు స్పామ్ ఫోల్డర్ చూడండి.",
    backToLogin: "← లాగిన్‌కు తిరిగి వెళ్లండి",
    checkYourEmail: "📧 మీ ఇమెయిల్‌ను చూడండి",
    resetEmailDelay: "పాస్‌వర్డ్ రీసెట్ లింక్ రావడానికి కొన్ని నిమిషాలు పట్టవచ్చు. స్పామ్ లేదా జంక్ ఫోల్డర్‌ను కూడా చూడండి.",
    weatherLoadFailed: "వాతావరణ సమాచారం లోడ్ కాలేదు.",
    locationUnsupported: "ఈ పరికరంలో స్థానాన్ని గుర్తించడం సాధ్యం కాదు.",
    localWeatherFailed: "మీ స్థానానికి వాతావరణ సమాచారం లోడ్ కాలేదు.",
    locationAccessNeeded: "స్థానిక వాతావరణం మరియు వ్యవసాయ సలహా కోసం స్థాన అనుమతిని ఇవ్వండి.",
    currentLocation: "ప్రస్తుత స్థానం",
    seasonKharif: "ఖరీఫ్",
    seasonRabi: "రబీ",
    seasonSummer: "వేసవి",
    rainValueLabel: "💧 వర్షం:",
    windValueLabel: "💨 గాలి:",
    conditionClearSky: "ఆకాశం నిర్మలంగా ఉంది",
    conditionMostlyClear: "ఎక్కువగా నిర్మలమైన ఆకాశం",
    conditionPartlyCloudy: "పాక్షికంగా మేఘావృతం",
    conditionCloudy: "మేఘావృతం",
    conditionFog: "పొగమంచు",
    conditionLightDrizzle: "తేలికపాటి చిరుజల్లు",
    conditionDrizzle: "చిరుజల్లు",
    conditionHeavyDrizzle: "భారీ చిరుజల్లు",
    conditionLightRain: "తేలికపాటి వర్షం",
    conditionRain: "వర్షం",
    conditionHeavyRain: "భారీ వర్షం",
    conditionRainShowers: "జల్లులతో కూడిన వర్షం",
    conditionHeavyShowers: "భారీ వర్షపు జల్లులు",
    conditionThunderstorm: "ఉరుములతో కూడిన వర్షం",
    conditionSevereThunderstorm: "తీవ్రమైన ఉరుములతో కూడిన వర్షం",
    conditionWeather: "వాతావరణం",
    sprayAdviceUnavailable: "పిచికారీ సలహా అందుబాటులో లేదు",
    irrigationAdviceUnavailable: "సాగునీటి సలహా అందుబాటులో లేదు",
    fieldWorkAdviceUnavailable: "పొలం పనుల సలహా అందుబాటులో లేదు",
    forecastRequiredSpray: "పురుగుమందు పిచికారీని ప్లాన్ చేయడానికి వాతావరణ సూచన అవసరం.",
    forecastRequiredIrrigation: "సాగునీటిని ప్లాన్ చేయడానికి వాతావరణ సూచన అవసరం.",
    refreshWeatherTryAgain: "వాతావరణ సమాచారాన్ని రిఫ్రెష్ చేసి మళ్లీ ప్రయత్నించండి.",
    avoidSpraying: "ఇప్పుడు పిచికారీ చేయవద్దు",
    rainWashSpray: "వర్షం పిచికారీని కడిగివేయవచ్చు. వర్షం లేని సమయం కోసం వేచి ఉండండి.",
    windSprayDrift: "గాలి చాలా బలంగా ఉంది; పిచికారీ దూరంగా వెళ్లే ప్రమాదం ఉంది.",
    unsuitableSprayTemperature: "సురక్షితమైన, సమర్థవంతమైన పిచికారీకి ఉష్ణోగ్రత అనుకూలంగా లేదు.",
    possibleSprayWindow: "పిచికారీకి అనుకూలమైన సమయం ఉండవచ్చు",
    sprayWindowAdvice: "{{time}} సమయంలో వాతావరణం అనుకూలంగా కనిపిస్తోంది. పిచికారీకి ముందు పురుగుమందు లేబుల్‌ను మళ్లీ చూడండి.",
    waitBeforeSpraying: "పిచికారీకి ముందు వేచి ఉండండి",
    noSprayWindow: "తదుపరి 24 గంటల్లో వర్షం తక్కువగా, గాలి తక్కువగా ఉండే నమ్మదగిన సమయం కనిపించలేదు.",
    delayIrrigation: "సాగునీటిని వాయిదా వేయండి",
    rainLikelyCheckField: "త్వరలో వర్షం వచ్చే అవకాశం ఉంది. నీరు పెట్టే ముందు వర్షం తర్వాత పొలాన్ని పరిశీలించండి.",
    checkCropMoisture: "పంట తేమను పరిశీలించండి",
    hotDryIrrigateSandy: "వేడి, పొడి వాతావరణం నేల తేమను త్వరగా తగ్గించవచ్చు. వేర్ల ప్రాంతం పొడిగా ఉంటే ఉదయాన్నే నీరు పెట్టండి.",
    highWaterDemand: "నీటి అవసరం ఎక్కువగా ఉండవచ్చు. నేల తేమను చూసి అవసరమైతే ఉదయాన్నే నీరు పెట్టండి.",
    avoidExcessWatering: "అధికంగా నీరు పెట్టవద్దు",
    soilMayHoldWater: "మీ నేల ఎక్కువసేపు నీటిని నిల్వ ఉంచవచ్చు. నీరు పెట్టే ముందు ఉపరితలం కింద తేమను చూడండి.",
    checkSoilBeforeWatering: "నీరు పెట్టే ముందు నేలను పరిశీలించండి",
    noUrgentIrrigation: "తక్షణ సాగునీటి అవసరం కనిపించడం లేదు. ముందుగా వేర్ల ప్రాంతంలోని తేమను చూడండి.",
    postponeFieldWork: "ముఖ్యమైన పొలం పనులను వాయిదా వేయండి",
    windRainFieldWork: "బలమైన గాలి లేదా వర్షం కోత, ఎరువు వేయడం, పరికరాల పనులను ప్రభావితం చేయవచ్చు.",
    fieldWorkPossible: "పొలం పనులు చేయవచ్చు",
    suitableContinueChecking: "వాతావరణం అనుకూలంగా కనిపిస్తోంది; అయినా స్థానిక ఆకాశ పరిస్థితులను గమనించండి.",
    veryHighTemperatureWarning: "చాలా అధిక ఉష్ణోగ్రత: మధ్యాహ్నం పిచికారీ చేయవద్దు; కార్మికులు, పశువులను కాపాడండి.",
    strongWindWarning: "బలమైన గాలి: తేలికపాటి వస్తువులను భద్రపరచండి, పిచికారీ చేయవద్దు.",
    rainAtLocationWarning: "గుర్తించిన ప్రాంతంలో వర్షం పడుతోంది.",
    highRainTodayWarning: "ఈ రోజు వర్షం వచ్చే అవకాశం ఎక్కువ. కోసిన పంటను, నిల్వ వస్తువులను కాపాడండి.",
    governmentSchemesTitle: "🏛️ ప్రభుత్వ పథకాలు",
    schemeTitlePmkisan: "ప్రధాన మంత్రి కిసాన్ సమ్మాన్ నిధి",
    schemeTitleInsurance: "ప్రధాన మంత్రి ఫసల్ బీమా యోజన",
    schemeTitleCredit: "కిసాన్ క్రెడిట్ కార్డ్",
    schemeTitleSoil: "నేల ఆరోగ్య కార్డు పథకం",
    schemeTitleIrrigation: "ప్రధాన మంత్రి కృషి సించాయీ యోజన",
    schemeTitleEnam: "ఈ-నామ్",
    governmentSchemesIntro: "రైతులకు ఉపయోగకరమైన ప్రభుత్వ పథకాలను కనుగొనండి.",
    searchSchemesPlaceholder: "పథకం, బీమా, రుణం, సాగునీటి కోసం వెతకండి...",
    schemeBenefitLabel: "ప్రయోజనం:",
    schemeEligibilityLabel: "అర్హత:",
    schemeDocumentsLabel: "పత్రాలు:",
    speakScheme: "🔊 వినండి",
    applyInfo: "దరఖాస్తు సమాచారం",
    schemeApplySoon: "దరఖాస్తు సమాచారం త్వరలో అందుబాటులో ఉంటుంది.",
    noSchemesFound: "పథకాలు కనబడలేదు",
    searchSchemesHint: "రుణం, బీమా, సాగునీరు, మార్కెట్ లేదా నేల అని వెతకండి.",
    schemeCategoryFinancial: "ఆర్థిక సహాయం",
    schemeCategoryInsurance: "పంట బీమా",
    schemeCategoryLoan: "రుణ సహాయం",
    schemeCategorySoil: "నేల పరీక్ష",
    schemeCategoryIrrigation: "సాగునీరు",
    schemeCategoryMarket: "మార్కెట్ సహాయం",
    schemeBenefitPmkisan: "అర్హులైన రైతులకు సంవత్సరానికి ₹6000 సహాయం.",
    schemeEligibilityPmkisan: "చెల్లుబాటు అయ్యే భూమి రికార్డులు ఉన్న చిన్న మరియు సన్నకారు రైతులు.",
    schemeDocumentsPmkisan: "ఆధార్, బ్యాంకు ఖాతా, భూమి వివరాలు.",
    schemeBenefitInsurance: "ప్రకృతి వైపరీత్యాల వల్ల పంట నష్టానికి రక్షణ.",
    schemeEligibilityInsurance: "ప్రకటించిన ప్రాంతాల్లో ప్రకటించిన పంటలు పండించే రైతులు.",
    schemeDocumentsInsurance: "ఆధార్, బ్యాంకు ఖాతా, పంట వివరాలు, భూమి వివరాలు.",
    schemeBenefitCredit: "తక్కువ వడ్డీతో స్వల్పకాలిక పంట రుణం.",
    schemeEligibilityCredit: "రైతులు, కౌలు రైతులు, భాగస్వామ్య రైతులు.",
    schemeDocumentsCredit: "ఆధార్, భూమి రికార్డులు, బ్యాంకు వివరాలు.",
    schemeBenefitSoil: "నేల పోషకాల నివేదిక మరియు ఎరువుల సలహా.",
    schemeEligibilityAllFarmers: "రైతులందరూ.",
    schemeDocumentsSoil: "రైతు వివరాలు మరియు భూమి వివరాలు.",
    schemeBenefitIrrigation: "మెరుగైన సాగునీరు మరియు నీటి వినియోగానికి సహాయం.",
    schemeEligibilityIrrigation: "సాగునీటి సదుపాయాల మెరుగుదల అవసరమైన రైతులు.",
    schemeBenefitEnam: "ఆన్‌లైన్ వ్యవసాయ మార్కెట్ వేదిక.",
    schemeEligibilityEnam: "నమోదిత మార్కెట్లలో ఉత్పత్తులు విక్రయించే రైతులు.",
    schemeDocumentsEnam: "రైతు గుర్తింపు, బ్యాంకు ఖాతా, ఉత్పత్తి వివరాలు.",
    cropDiseasePageTitle: "🌿 పంట వ్యాధి గుర్తింపు",
    cropDiseasePageIntro: "AI ఆధారిత సలహా కోసం పంట ఫోటో తీయండి లేదా అప్‌లోడ్ చేయండి.",
    cropNameOptional: "పంట పేరు (ఐచ్ఛికం)",
    cropNameExample: "ఉదాహరణ: పత్తి, వరి",
    cropOrLeafPhoto: "పంట లేదా ఆకు ఫోటో",
    imageAutoEnhancement: "సాధ్యమైనప్పుడు యాప్ ప్రకాశం, కాంట్రాస్ట్ మరియు స్పష్టతను ఆటోమేటిక్‌గా మెరుగుపరుస్తుంది.",
    processingPhoto: "ఫోటోను ప్రాసెస్ చేస్తోంది...",
    detectDiseaseButton: "🔍 వ్యాధిని గుర్తించండి",
    detectedCrop: "గుర్తించిన పంట",
    possibleCondition: "సంభావ్య సమస్య",
    visibleSymptoms: "కనిపించే లక్షణాలు",
    likelyCauses: "సంభావ్య కారణాలు",
    immediateActions: "తక్షణ చర్యలు",
    recommendedPesticide: "సిఫార్సు చేసిన పురుగుమందు",
    availablePesticides: "అందుబాటులో ఉన్న పురుగుమందులు",
    recommendedFertilizer: "సిఫార్సు చేసిన ఎరువు",
    availableFertilizers: "అందుబాటులో ఉన్న ఎరువులు",
    treatmentGuidance: "చికిత్స సూచనలు",
    prevention: "నివారణ",
    imageRequired: "ముందుగా ప్రభావితమైన ఆకు లేదా మొక్క ఫోటోను అప్‌లోడ్ చేయండి.",
    photoNotClearPlant: "ఫోటోలో పంట లేదా మొక్క స్పష్టంగా గుర్తించబడలేదు. ప్రభావితమైన ఆకును చూపిస్తూ మరో ఫోటో తీయండి.",
    imageImproveTimeout: "చిత్ర మెరుగుదలకు ఎక్కువ సమయం పట్టింది. దయచేసి మళ్లీ ప్రయత్నించండి.",
    diseaseDetectionFailed: "వ్యాధి గుర్తింపు విఫలమైంది. మరో ఫోటోతో ప్రయత్నించండి.",
    weatherLoading: "వాతావరణం లోడ్ అవుతోంది",
    detectingLocation: "మీ స్థానాన్ని గుర్తిస్తోంది",
    dashboardLink: "← డ్యాష్‌బోర్డ్",
    farmWeather: "🌦️ వ్యవసాయ వాతావరణం",
    localForecastAdvice: "స్థానిక వాతావరణ సూచన మరియు వ్యవసాయ సలహా.",
    detecting: "గుర్తిస్తోంది...",
    refreshLocation: "📍 స్థానాన్ని మళ్లీ గుర్తించండి",
    locationNotDetected: "స్థానం గుర్తించబడలేదు",
    locationPermissionNeeded: "స్థాన అనుమతి అవసరం",
    enableLocationWeather: "స్థానిక వాతావరణం మరియు వ్యవసాయ సలహా కోసం స్థాన అనుమతిని ప్రారంభించండి.",
    detectMyLocation: "నా స్థానాన్ని గుర్తించండి",
    currentTemperature: "ప్రస్తుత ఉష్ణోగ్రత",
    feelsLike: "అనిపించే ఉష్ణోగ్రత",
    rainLabel: "🌧️ వర్షం",
    windLabel: "💨 గాలి",
    windGustLabel: "💨 గాలి వేగపు జోరు",
    weatherWarnings: "⚠️ వాతావరణ హెచ్చరికలు",
    todaysFarmAdvice: "🌾 నేటి వ్యవసాయ సలహా",
    pesticideLabelInstructions: "పురుగుమందు లేబుల్ మరియు స్థానిక వ్యవసాయ అధికారి సూచనలను పాటించండి.",
    next12Hours: "🕒 తదుపరి 12 గంటలు",
    forecast7Day: "📅 7 రోజుల వాతావరణ సూచన",
    rainChance: "🌧️ వర్షం పడే అవకాశం:",
    cropSuggestions: "🌱 పంట సూచనలు",
    cropSuggestionsBasis: "కాలం, సేవ్ చేసిన నేల రకం మరియు అందుబాటులోని మార్కెట్ ధరల ఆధారంగా.",
    seasonLabel: "కాలం",
    matchesSavedSoil: "సేవ్ చేసిన నేల రకానికి సరిపోతుంది",
    suitableCurrentSeason: "ప్రస్తుత కాలానికి అనుకూలం",
    marketPriceLabel: "మార్కెట్ ధర:",
    marketPriceUnavailable: "మార్కెట్ ధరల సమాచారం ఇంకా అందుబాటులో లేదు. ప్రస్తుతం కాలం మరియు నేల రకం ఆధారంగా సూచనలు ఇస్తున్నాం.",
    cropSelectionFactors: "పంట ఎంపిక నీరు, విత్తనాల లభ్యత, స్థానిక తెగుళ్లు, ఖర్చులు మరియు అధికారిక వ్యవసాయ సలహాపై కూడా ఆధారపడి ఉంటుంది.",
    cropHelp: "పంట సహాయం",
    farmProfile: "వ్యవసాయ ప్రొఫైల్",
    roleSelectionTitle: "AgriSaathiని ఎలా ఉపయోగించాలో ఎంచుకోండి",
    roleSelectionSubtitle: "వ్యవసాయం కోసం మీ స్మార్ట్ సహచరుడు",
    selectRoleToContinue: "కొనసాగించడానికి మీ పాత్రను ఎంచుకోండి",
    roleFarmer: "రైతు",
    roleFarmerDescription: "పంట సమాచారం, వ్యాధి గుర్తింపు, వాతావరణం, మార్కెట్ ధరలు మరియు స్థానిక వ్యవసాయ ఉత్పత్తులను పొందండి.",
    roleDealer: "డీలర్",
    roleDealerDescription: "ఉత్పత్తులు, నిల్వ, రైతుల ఆర్డర్లు మరియు అమ్మకాలను నిర్వహించండి.",
    roleAdmin: "నిర్వాహకుడు",
    roleAdminDescription: "రైతులు, డీలర్లు, ఉత్పత్తులు, నివేదికలు, ఆమోదాలు మరియు వ్యవస్థ కార్యకలాపాలను నిర్వహించండి.",
    continueAsRole: "{{role}}గా కొనసాగండి",
    openingLogin: "లాగిన్ తెరుస్తోంది...",
    simpleToUse: "ఉపయోగించడానికి సులభం",
    farmerFriendly: "రైతులకు అనుకూలం",
    secureAccess: "సురక్షిత ప్రవేశం",
    selectLanguage: "భాషను ఎంచుకోండి",
    chooseLanguage: "మీకు ఇష్టమైన భాషను ఎంచుకోండి",
    smartFarmingCompanion: "స్మార్ట్ వ్యవసాయ సహాయకుడు",
    welcomeFarmer: "స్వాగతం రైతు గారు",
    chooseService: "క్రింది సేవను ఎంచుకోండి",

    login: "లాగిన్",
    logout: "లాగౌట్",
    createAccount: "ఖాతా సృష్టించండి",
    email: "ఇమెయిల్",
    password: "పాస్‌వర్డ్",
    dashboard: "డాష్‌బోర్డ్",

    home: "హోమ్",
    orders: "ఆర్డర్లు",
    notifications: "సూచనలు",
    community: "కమ్యూనిటీ",
    profile: "ప్రొఫైల్",
    settings: "సెట్టింగ్స్",

    weather: "వాతావరణం",
    cropDisease: "పంట వ్యాధి",
    marketPrices: "మార్కెట్ ధరలు",
    govtSchemes: "ప్రభుత్వ పథకాలు",
    farmerProfile: "రైతు ప్రొఫైల్",
    dealerProducts: "డీలర్లు",
    myOrders: "నా ఆర్డర్లు",
    voiceAssistant: "వాయిస్ సహాయకుడు",

    scanCrop: "పంటను స్కాన్ చేయండి",
    localDealers: "సమీప డీలర్లు",
    buyProducts: "ఉత్పత్తులు కొనండి",
    checkMandi: "మండి ధరలు చూడండి",
    trackPurchase: "కొనుగోలు స్థితి చూడండి",
    farmingServices: "వ్యవసాయ సేవలు",

    back: "వెనక్కి",
    refresh: "రిఫ్రెష్",
    loading: "లోడ్ అవుతోంది...",
    save: "సేవ్ చేయండి",
    cancel: "రద్దు చేయండి",
    continue: "కొనసాగండి",
    retry: "మళ్లీ ప్రయత్నించండి",

    languageChanged: "భాష విజయవంతంగా మార్చబడింది.",
    noInformation: "సమాచారం అందుబాటులో లేదు.",
    openingAgriSaathi: "అగ్రిసాథి తెరుచుకుంటోంది...",
    latestOrder: "తాజా ఆర్డర్",
    farmProduct: "వ్యవసాయ ఉత్పత్తి",
    quantity: "పరిమాణం",
    trackOrder: "ఆర్డర్‌ను చూడండి",
    schemes: "పథకాలు",
    nearbyServices: "సమీప వ్యవసాయ సేవలు",
    nearbyServicesDescription: "సమీపంలోని వ్యవసాయ కార్యాలయాలు, నేల పరీక్ష కేంద్రాలు, పరికర సేవలు మరియు ఇతర రైతు సహాయాన్ని కనుగొనండి.",
    openNearbyServices: "సమీప సేవలను తెరవండి",
    voice: "వాయిస్",
    waitingForDealer: "డీలర్ స్పందన కోసం వేచి ఉంది",
    dealerAccepted: "డీలర్ అంగీకరించారు",
    orderRejected: "ఆర్డర్ తిరస్కరించబడింది",
    markedDelivered: "డెలివరీ చేసినట్లు గుర్తించారు",
    deliveryConfirmed: "డెలివరీ నిర్ధారించబడింది",
    paymentConfirmed: "చెల్లింపు నిర్ధారించబడింది",
    completed: "పూర్తైంది",
    cancelled: "రద్దైంది",
    orderUpdate: "ఆర్డర్ సమాచారం",
    appLanguage: "యాప్ భాష",
    changeLanguageAnytime: "రైతు మాడ్యూల్ భాషను ఎప్పుడైనా మార్చండి.",
    languageUpdated: "యాప్ భాష మార్చబడింది.",
    myProfile: "నా ప్రొఫైల్",
    personalFarmInformation: "వ్యక్తిగత మరియు వ్యవసాయ సమాచారం.",    goodMorning: "శుభోదయం",
    goodAfternoon: "శుభ మధ్యాహ్నం",
    goodEvening: "శుభ సాయంత్రం",
    farmer: "రైతు",
    farmLocationNotAdded: "వ్యవసాయ స్థలం జోడించలేదు",
    openNotifications: "సూచనలు తెరవండి",
    loadingLocalWeather: "స్థానిక వాతావరణం లోడ్ అవుతోంది...",
    currentWeather: "ప్రస్తుత వాతావరణం",
    humidity: "తేమ",
    weatherUnavailable: "వాతావరణ సమాచారం అందుబాటులో లేదు",
    allowLocationForWeather: "స్థానిక వాతావరణం కోసం లొకేషన్ అనుమతించండి.",
    openVoiceAssistant: "అగ్రిసాథి వాయిస్ సహాయకుడిని తెరవండి",
    askAgriSaathi: "అగ్రిసాథిని అడగండి",
    speakInYourLanguage: "మైక్రోఫోన్ నొక్కి మీ భాషలో మాట్లాడండి.",
    startSpeaking: "మాట్లాడడం ప్రారంభించండి",
    checkDisease: "వ్యాధిని పరీక్షించండి",
    prices: "ధరలు",
    whatDoYouNeed: "మీకు ఏమి కావాలి?",
    loadingMarketPrice: "పంట మార్కెట్ ధర లోడ్ అవుతోంది...",
    marketPrice: "మార్కెట్ ధర",
    cropPrices: "పంట ధరలు",
    noCurrentMarketRecord: "ప్రస్తుత ధర వివరాలు లభించలేదు. అన్ని పంటలు మరియు మండీలను చూడటానికి మార్కెట్ పేజీని తెరవండి.",
    viewMarketPrices: "మార్కెట్ ధరలు చూడండి",
    localMarketPrice: "స్థానిక మార్కెట్ ధర",
    localMandi: "స్థానిక మండి",
    nearbyMarket: "సమీప మార్కెట్",
    perQuintal: "క్వింటాల్‌కు",
    minimum: "కనిష్ఠం",
    maximum: "గరిష్ఠం",
    compareAllMarkets: "అన్ని మార్కెట్లను పోల్చండి",

  },

  hi: {
    productLoading: "उत्पाद लोड हो रहा है",
    productUnavailable: "उत्पाद उपलब्ध नहीं है",
    viewOtherProducts: "अन्य उत्पाद देखें",
    productInformation: "उत्पाद की जानकारी",
    dealerLabel: "🏪 डीलर",
    selectQuantity: "मात्रा चुनें",
    totalLabel: "कुल:",
    sendingOrderRequest: "अनुरोध भेजा जा रहा है...",
    paymentCashOnDelivery: "भुगतान: सामान मिलने पर नकद",
    categorySeeds: "बीज",
    categoryFertilizer: "उर्वरक",
    categoryPesticide: "कीटनाशक",
    categoryTools: "औज़ार",
    categoryFeed: "पशु आहार",
    categoryAll: "सभी",
    noProductsFound: "कोई उत्पाद नहीं मिला",
    tryDifferentProduct: "दूसरे उत्पाद का नाम या श्रेणी खोजें।",
    noDealerProducts: "पास के डीलरों ने अभी उपलब्ध उत्पाद नहीं जोड़े हैं।",
    clearSearch: "खोज साफ़ करें",
    refreshProducts: "उत्पाद रीफ़्रेश करें",
    noProductImage: "उत्पाद की तस्वीर नहीं है",
    lowStock: "कम स्टॉक",
    inStock: "स्टॉक में",
    priceLabel: "कीमत",
    perUnit: "प्रति {{unit}}",
    availableLabel: "उपलब्ध",
    unitsLabel: "इकाइयाँ",
    locationNotAvailable: "स्थान उपलब्ध नहीं है",
    callDealer: "📞 डीलर को कॉल करें",
    approvedDealer: "✓ स्वीकृत डीलर",
    viewProductDetails: "👁️ उत्पाद का विवरण देखें",
    sendingOrder: "भेजा जा रहा है...",
    requestOrder: "ऑर्डर का अनुरोध करें",
    decreaseQuantity: "मात्रा घटाएँ",
    increaseQuantity: "मात्रा बढ़ाएँ",
    nearbyProductsLoading: "पास के उत्पाद खोजे जा रहे हैं",
    pleaseWait: "कृपया प्रतीक्षा करें...",
    localMarketplace: "🏪 स्थानीय बाज़ार",
    marketplaceIntro: "बीज, उर्वरक और खेती के उत्पाद।",
    myOrdersButton: "🛒 मेरे ऑर्डर",
    nearLabel: "📍 पास में",
    registeredArea: "आपका पंजीकृत क्षेत्र",
    searchProduct: "🔍 उत्पाद खोजें",
    marketplaceSearchPlaceholder: "यूरिया, कपास के बीज, कीटनाशक...",
    speak: "🎤 बोलें",
    voiceSearchLabel: "आवाज़ से खोज:",
    nearbyProducts: "पास के उत्पाद",
    productsFound: "मिले",
    orderRequestSent: "ऑर्डर अनुरोध भेज दिया गया। डीलर के जवाब के लिए मेरे ऑर्डर देखें।",
    orderAccessBlocked: "Firebase नियमों के कारण ऑर्डर का उपयोग रोका गया है।",
    orderRequestFailed: "ऑर्डर अनुरोध नहीं भेजा जा सका।",
    marketLoading: "बाजार भाव लोड हो रहे हैं",
    detectingMarketArea: "आपका बाजार क्षेत्र पता किया जा रहा है",
    localCropPricesTitle: "📈 स्थानीय फसल के भाव",
    marketPageIntro: "किसानों की आसानी के लिए फसल की तस्वीरों सहित सरकारी मंडी भाव।",
    savedFarmerLocation: "सहेजा गया किसान स्थान",
    cropCount: "फसलें",
    marketCount: "बाजार",
    priceRecords: "भाव रिकॉर्ड",
    averagePrice: "औसत भाव",
    yourMainCrop: "आपकी मुख्य फसल",
    showPrices: "भाव दिखाएँ",
    searchAnyCrop: "🔍 कोई भी फसल खोजें",
    cropSearchPlaceholder: "कपास, धान, टमाटर, मक्का...",
    allDistricts: "सभी जिले",
    allMarkets: "सभी बाजार",
    latestRecords: "नवीनतम रिकॉर्ड",
    highestPrice: "सबसे अधिक भाव",
    lowestPrice: "सबसे कम भाव",
    marketSummaryTitle: "बाजार भाव का सारांश",
    bestPrice: "सबसे अच्छा भाव",
    averageLabel: "औसत",
    bestPlace: "सबसे अच्छा बाजार",
    viewCommodityDetails: "{{crop}} का विवरण देखें",
    mandiPriceDetails: "मंडी भाव का विवरण",
    refreshing: "रीफ़्रेश हो रहा है...",
    noMarketRecords: "बाजार का कोई रिकॉर्ड उपलब्ध नहीं है।",
    minPrice: "न्यूनतम",
    modalPrice: "मॉडल भाव",
    maxPrice: "अधिकतम",
    dateLabel: "तारीख:",
    notAvailable: "उपलब्ध नहीं",
    openMarket: "बाजार खोलें",
    nearbySellingPlaces: "पास के बिक्री केंद्र",
    searchInMaps: "मैप में खोजें",
    searchingNearbyPlaces: "पास के बिक्री केंद्र खोजे जा रहे हैं...",
    noMappedPlaces: "मैप पर पास का बिक्री केंद्र नहीं मिला।",
    addressNotAvailable: "पता उपलब्ध नहीं है",
    distanceLabel: "दूरी:",
    directions: "रास्ता देखें",
    call: "कॉल करें",
    categoryAllCrops: "सभी फसलें",
    categoryGrains: "अनाज",
    categoryPulses: "दालें",
    categoryVegetables: "सब्ज़ियाँ",
    categoryFruits: "फल",
    categorySpices: "मसाले",
    categoryOilseeds: "तिलहन",
    categoryFibre: "रेशेदार फसलें",
    cropNameSort: "फसल का नाम",
    cropPriceSummary: "फसल भाव का सारांश",
    loadingPrices: "भाव लोड हो रहे हैं...",
    noCropPricesForFilters: "चुने गए फ़िल्टर के लिए फसल भाव नहीं मिले।",
    recordCount: "रिकॉर्ड",
    marketCountLower: "बाजार",
    highest: "सबसे अधिक",
    lowest: "सबसे कम",
    checkBeforeSelling: "बेचने से पहले जाँचें",
    marketInfoUnavailable: "बाजार की जानकारी लोड नहीं हो सकी।",
    locationFallback: "स्थान उपलब्ध नहीं है। सहेजे गए प्रोफ़ाइल स्थान के भाव दिखाए जा रहे हैं।",
    exactLocationFallback: "सटीक स्थान पता नहीं चला। सहेजे गए प्रोफ़ाइल स्थान के भाव दिखाए जा रहे हैं।",
    locationPermissionNearby: "पास के बाजार खोजने के लिए स्थान की अनुमति दें। सहेजा गया प्रोफ़ाइल स्थान इस्तेमाल हो रहा है।",
    noCurrentMandiPrices: "इस स्थान के लिए मौजूदा सरकारी मंडी भाव नहीं मिले।",
    govtPricesUnavailable: "सरकारी मंडी भाव लोड नहीं हो सके।",
    locationRequiredSelling: "पास के बिक्री केंद्र खोजने के लिए स्थान ज़रूरी है।",
    noMappedSellingPoints: "पास में मैप किया गया बिक्री केंद्र नहीं मिला। मैप में खोजें।",
    nearbySellingUnavailable: "पास के बिक्री केंद्र अस्थायी रूप से उपलब्ध नहीं हैं। आप मैप में खोज सकते हैं।",
    sellingTypeMarket: "बाजार",
    sellingTypeRiceMill: "चावल मिल",
    sellingTypeOilMill: "तेल मिल",
    sellingTypeCottonMill: "कपास मिल",
    sellingTypeDalMill: "दाल मिल",
    sellingTypeFlourMill: "आटा मिल",
    sellingTypeMarketplace: "बाजार स्थल",
    cropPriceSummaryUnavailable: "भाव उपलब्ध नहीं है",
    goodMarketPrice: "अच्छा बाजार भाव",
    compareMarkets: "बाजारों की तुलना करें",
    forgotPasswordTitle: "पासवर्ड भूल गए?",
    forgotPasswordIntro: "अपना पंजीकृत ईमेल पता दर्ज करें। हम आपको पासवर्ड रीसेट लिंक भेजेंगे।",
    registeredEmail: "पंजीकृत ईमेल",
    enterEmail: "अपना ईमेल दर्ज करें",
    sendResetLink: "रीसेट लिंक भेजें",
    sendingResetLink: "रीसेट लिंक भेजा जा रहा है...",
    resetEmailRequired: "कृपया अपना ईमेल पता दर्ज करें।",
    resetEmailInvalid: "कृपया मान्य ईमेल पता दर्ज करें।",
    resetEmailSent: "यदि इस ईमेल से खाता मौजूद है, तो पासवर्ड रीसेट लिंक भेज दिया गया है। अपना इनबॉक्स और स्पैम फ़ोल्डर देखें।",
    backToLogin: "← लॉगिन पर वापस जाएँ",
    checkYourEmail: "📧 अपना ईमेल देखें",
    resetEmailDelay: "पासवर्ड रीसेट लिंक आने में कुछ मिनट लग सकते हैं। स्पैम या जंक फ़ोल्डर भी देखें।",
    weatherLoadFailed: "मौसम की जानकारी लोड नहीं हो सकी।",
    locationUnsupported: "इस उपकरण पर स्थान पता करना उपलब्ध नहीं है।",
    localWeatherFailed: "आपके स्थान का मौसम लोड नहीं हो सका।",
    locationAccessNeeded: "स्थानीय मौसम और खेती की सलाह के लिए स्थान की अनुमति दें।",
    currentLocation: "वर्तमान स्थान",
    seasonKharif: "खरीफ़",
    seasonRabi: "रबी",
    seasonSummer: "ग्रीष्म",
    rainValueLabel: "💧 बारिश:",
    windValueLabel: "💨 हवा:",
    conditionClearSky: "आसमान साफ़",
    conditionMostlyClear: "अधिकतर साफ़",
    conditionPartlyCloudy: "आंशिक रूप से बादल",
    conditionCloudy: "बादल छाए हैं",
    conditionFog: "कोहरा",
    conditionLightDrizzle: "हल्की बूंदाबांदी",
    conditionDrizzle: "बूंदाबांदी",
    conditionHeavyDrizzle: "तेज़ बूंदाबांदी",
    conditionLightRain: "हल्की बारिश",
    conditionRain: "बारिश",
    conditionHeavyRain: "तेज़ बारिश",
    conditionRainShowers: "बारिश की बौछारें",
    conditionHeavyShowers: "तेज़ बौछारें",
    conditionThunderstorm: "गरज के साथ बारिश",
    conditionSevereThunderstorm: "तेज़ गरज के साथ बारिश",
    conditionWeather: "मौसम",
    sprayAdviceUnavailable: "छिड़काव की सलाह उपलब्ध नहीं है",
    irrigationAdviceUnavailable: "सिंचाई की सलाह उपलब्ध नहीं है",
    fieldWorkAdviceUnavailable: "खेत के काम की सलाह उपलब्ध नहीं है",
    forecastRequiredSpray: "कीटनाशक छिड़काव की योजना बनाने से पहले मौसम पूर्वानुमान ज़रूरी है।",
    forecastRequiredIrrigation: "सिंचाई की योजना बनाने से पहले मौसम पूर्वानुमान ज़रूरी है।",
    refreshWeatherTryAgain: "मौसम की जानकारी रीफ़्रेश करके फिर कोशिश करें।",
    avoidSpraying: "अभी छिड़काव न करें",
    rainWashSpray: "बारिश से दवा धुल सकती है। सूखे मौसम का इंतज़ार करें।",
    windSprayDrift: "हवा बहुत तेज़ है और दवा बहकर दूसरी जगह जा सकती है।",
    unsuitableSprayTemperature: "सुरक्षित और असरदार छिड़काव के लिए तापमान उपयुक्त नहीं है।",
    possibleSprayWindow: "छिड़काव के लिए संभावित समय",
    sprayWindowAdvice: "{{time}} के आसपास मौसम उपयुक्त लग रहा है। छिड़काव से पहले कीटनाशक का लेबल फिर पढ़ें।",
    waitBeforeSpraying: "छिड़काव से पहले इंतज़ार करें",
    noSprayWindow: "अगले 24 घंटों में सूखा और कम हवा वाला भरोसेमंद समय नहीं मिला।",
    delayIrrigation: "सिंचाई टालें",
    rainLikelyCheckField: "जल्द बारिश हो सकती है। पानी देने से पहले बारिश के बाद खेत देखें।",
    checkCropMoisture: "फसल की नमी जाँचें",
    hotDryIrrigateSandy: "गर्मी और सूखे से नमी जल्दी घट सकती है। जड़ क्षेत्र सूखा हो तो सुबह जल्दी सिंचाई करें।",
    highWaterDemand: "पानी की ज़रूरत अधिक हो सकती है। मिट्टी की नमी जाँचें और ज़रूरत पर सुबह सिंचाई करें।",
    avoidExcessWatering: "ज़्यादा पानी देने से बचें",
    soilMayHoldWater: "आपकी मिट्टी पानी अधिक समय तक रोक सकती है। सिंचाई से पहले सतह के नीचे नमी जाँचें।",
    checkSoilBeforeWatering: "पानी देने से पहले मिट्टी जाँचें",
    noUrgentIrrigation: "मौसम में तुरंत सिंचाई की ज़रूरत नहीं दिखती। पहले जड़ क्षेत्र की नमी जाँचें।",
    postponeFieldWork: "मुख्य खेत के काम टालें",
    windRainFieldWork: "तेज़ हवा या बारिश से कटाई, खाद डालने और मशीन के काम प्रभावित हो सकते हैं।",
    fieldWorkPossible: "खेत का काम किया जा सकता है",
    suitableContinueChecking: "मौसम अनुकूल लगता है, फिर भी स्थानीय आसमान की स्थिति देखते रहें।",
    veryHighTemperatureWarning: "बहुत अधिक तापमान: दोपहर में छिड़काव न करें और मज़दूरों व पशुओं को सुरक्षित रखें।",
    strongWindWarning: "तेज़ हवा: हल्की चीज़ें सुरक्षित रखें और छिड़काव से बचें।",
    rainAtLocationWarning: "पता की गई जगह पर बारिश हो रही है।",
    highRainTodayWarning: "आज बारिश की संभावना अधिक है: कटी फसल और भंडारित सामग्री सुरक्षित रखें।",
    governmentSchemesTitle: "🏛️ सरकारी योजनाएँ",
    schemeTitlePmkisan: "प्रधानमंत्री किसान सम्मान निधि",
    schemeTitleInsurance: "प्रधानमंत्री फसल बीमा योजना",
    schemeTitleCredit: "किसान क्रेडिट कार्ड",
    schemeTitleSoil: "मृदा स्वास्थ्य कार्ड योजना",
    schemeTitleIrrigation: "प्रधानमंत्री कृषि सिंचाई योजना",
    schemeTitleEnam: "ई-नाम",
    governmentSchemesIntro: "किसानों के लिए उपयोगी सरकारी योजनाएँ खोजें।",
    searchSchemesPlaceholder: "योजना, बीमा, ऋण, सिंचाई खोजें...",
    schemeBenefitLabel: "लाभ:",
    schemeEligibilityLabel: "पात्रता:",
    schemeDocumentsLabel: "दस्तावेज़:",
    speakScheme: "🔊 सुनें",
    applyInfo: "आवेदन की जानकारी",
    schemeApplySoon: "आवेदन की जानकारी जल्द उपलब्ध होगी।",
    noSchemesFound: "कोई योजना नहीं मिली",
    searchSchemesHint: "ऋण, बीमा, सिंचाई, बाजार या मिट्टी खोजकर देखें।",
    schemeCategoryFinancial: "वित्तीय सहायता",
    schemeCategoryInsurance: "फसल बीमा",
    schemeCategoryLoan: "ऋण सहायता",
    schemeCategorySoil: "मिट्टी की जाँच",
    schemeCategoryIrrigation: "सिंचाई",
    schemeCategoryMarket: "बाजार सहायता",
    schemeBenefitPmkisan: "पात्र किसानों को हर साल ₹6000 की सहायता।",
    schemeEligibilityPmkisan: "वैध भूमि रिकॉर्ड वाले छोटे और सीमांत किसान।",
    schemeDocumentsPmkisan: "आधार, बैंक खाता, भूमि का विवरण।",
    schemeBenefitInsurance: "प्राकृतिक आपदाओं से फसल नुकसान की सुरक्षा।",
    schemeEligibilityInsurance: "अधिसूचित क्षेत्रों में अधिसूचित फसलें उगाने वाले किसान।",
    schemeDocumentsInsurance: "आधार, बैंक खाता, फसल और भूमि का विवरण।",
    schemeBenefitCredit: "कम ब्याज पर अल्पकालिक फसल ऋण।",
    schemeEligibilityCredit: "किसान, किरायेदार किसान और बटाईदार।",
    schemeDocumentsCredit: "आधार, भूमि रिकॉर्ड, बैंक विवरण।",
    schemeBenefitSoil: "मिट्टी के पोषक तत्वों की रिपोर्ट और उर्वरक सलाह।",
    schemeEligibilityAllFarmers: "सभी किसान।",
    schemeDocumentsSoil: "किसान और भूमि का विवरण।",
    schemeBenefitIrrigation: "बेहतर सिंचाई और पानी के उपयोग के लिए सहायता।",
    schemeEligibilityIrrigation: "सिंचाई में सुधार की जरूरत वाले किसान।",
    schemeBenefitEnam: "ऑनलाइन कृषि बाजार मंच।",
    schemeEligibilityEnam: "पंजीकृत बाजारों में उपज बेचने वाले किसान।",
    schemeDocumentsEnam: "किसान पहचान पत्र, बैंक खाता, उपज का विवरण।",
    cropDiseasePageTitle: "🌿 फसल रोग पहचान",
    cropDiseasePageIntro: "AI आधारित सलाह के लिए फसल की तस्वीर लें या अपलोड करें।",
    cropNameOptional: "फसल का नाम (वैकल्पिक)",
    cropNameExample: "उदाहरण: कपास, धान",
    cropOrLeafPhoto: "फसल या पत्ती की तस्वीर",
    imageAutoEnhancement: "संभव होने पर ऐप चमक, कंट्रास्ट और स्पष्टता को अपने आप बेहतर करेगा।",
    processingPhoto: "तस्वीर संसाधित हो रही है...",
    detectDiseaseButton: "🔍 रोग पहचानें",
    detectedCrop: "पहचानी गई फसल",
    possibleCondition: "संभावित समस्या",
    visibleSymptoms: "दिखाई देने वाले लक्षण",
    likelyCauses: "संभावित कारण",
    immediateActions: "तुरंत किए जाने वाले काम",
    recommendedPesticide: "सुझाया गया कीटनाशक",
    availablePesticides: "उपलब्ध कीटनाशक उत्पाद",
    recommendedFertilizer: "सुझाया गया उर्वरक",
    availableFertilizers: "उपलब्ध उर्वरक उत्पाद",
    treatmentGuidance: "उपचार संबंधी सलाह",
    prevention: "बचाव",
    imageRequired: "पहले प्रभावित पत्ती या पौधे की तस्वीर अपलोड करें।",
    photoNotClearPlant: "तस्वीर में फसल या पौधा स्पष्ट रूप से नहीं पहचाना गया। प्रभावित पत्ती दिखाते हुए दूसरी तस्वीर लें।",
    imageImproveTimeout: "तस्वीर सुधारने में बहुत समय लगा। कृपया फिर कोशिश करें।",
    diseaseDetectionFailed: "रोग पहचान नहीं हो सकी। दूसरी तस्वीर के साथ फिर कोशिश करें।",
    weatherLoading: "मौसम लोड हो रहा है",
    detectingLocation: "आपका स्थान पता किया जा रहा है",
    dashboardLink: "← डैशबोर्ड",
    farmWeather: "🌦️ खेत का मौसम",
    localForecastAdvice: "स्थानीय मौसम पूर्वानुमान और कृषि सलाह।",
    detecting: "पता लगाया जा रहा है...",
    refreshLocation: "📍 स्थान फिर से पता करें",
    locationNotDetected: "स्थान पता नहीं चला",
    locationPermissionNeeded: "स्थान की अनुमति आवश्यक है",
    enableLocationWeather: "स्थानीय मौसम और खेती की सलाह पाने के लिए स्थान की अनुमति दें।",
    detectMyLocation: "मेरा स्थान पता करें",
    currentTemperature: "वर्तमान तापमान",
    feelsLike: "महसूस होने वाला तापमान",
    rainLabel: "🌧️ बारिश",
    windLabel: "💨 हवा",
    windGustLabel: "💨 हवा का झोंका",
    weatherWarnings: "⚠️ मौसम की चेतावनी",
    todaysFarmAdvice: "🌾 आज की खेती की सलाह",
    pesticideLabelInstructions: "कीटनाशक के लेबल और स्थानीय कृषि अधिकारी के निर्देशों का पालन करें।",
    next12Hours: "🕒 अगले 12 घंटे",
    forecast7Day: "📅 7 दिनों का पूर्वानुमान",
    rainChance: "🌧️ बारिश की संभावना:",
    cropSuggestions: "🌱 फसल सुझाव",
    cropSuggestionsBasis: "मौसम, सहेजी गई मिट्टी के प्रकार और उपलब्ध बाजार भाव के आधार पर।",
    seasonLabel: "मौसम",
    matchesSavedSoil: "सहेजी गई मिट्टी के प्रकार के अनुकूल",
    suitableCurrentSeason: "वर्तमान मौसम के लिए उपयुक्त",
    marketPriceLabel: "बाजार भाव:",
    marketPriceUnavailable: "बाजार भाव की जानकारी अभी उपलब्ध नहीं है। सुझाव फिलहाल मौसम और मिट्टी के प्रकार पर आधारित हैं।",
    cropSelectionFactors: "फसल का चुनाव पानी, बीज की उपलब्धता, स्थानीय कीट, लागत और आधिकारिक कृषि सलाह पर भी निर्भर करता है।",
    cropHelp: "फसल सहायता",
    farmProfile: "खेत की प्रोफ़ाइल",
    roleSelectionTitle: "चुनें कि आप AgriSaathi का उपयोग कैसे करेंगे",
    roleSelectionSubtitle: "कृषि के लिए आपका स्मार्ट साथी",
    selectRoleToContinue: "जारी रखने के लिए अपनी भूमिका चुनें",
    roleFarmer: "किसान",
    roleFarmerDescription: "फसल की जानकारी, रोग पहचान, मौसम, बाजार भाव और स्थानीय कृषि उत्पाद देखें।",
    roleDealer: "डीलर",
    roleDealerDescription: "उत्पाद, स्टॉक, किसानों के ऑर्डर और बिक्री प्रबंधित करें।",
    roleAdmin: "व्यवस्थापक",
    roleAdminDescription: "किसानों, डीलरों, उत्पादों, रिपोर्ट, अनुमोदन और सिस्टम गतिविधियों का प्रबंधन करें।",
    continueAsRole: "{{role}} के रूप में जारी रखें",
    openingLogin: "लॉगिन खुल रहा है...",
    simpleToUse: "उपयोग में आसान",
    farmerFriendly: "किसान-अनुकूल",
    secureAccess: "सुरक्षित पहुंच",
    selectLanguage: "भाषा चुनें",
    chooseLanguage: "अपनी पसंदीदा भाषा चुनें",
    smartFarmingCompanion: "स्मार्ट खेती साथी",
    welcomeFarmer: "स्वागत है किसान",
    chooseService: "नीचे एक सेवा चुनें",

    login: "लॉगिन",
    logout: "लॉगआउट",
    createAccount: "खाता बनाएं",
    email: "ईमेल",
    password: "पासवर्ड",
    dashboard: "डैशबोर्ड",

    home: "होम",
    orders: "ऑर्डर",
    notifications: "सूचनाएं",
    community: "समुदाय",
    profile: "प्रोफाइल",
    settings: "सेटिंग्स",

    weather: "मौसम",
    cropDisease: "फसल रोग",
    marketPrices: "बाजार भाव",
    govtSchemes: "सरकारी योजनाएं",
    farmerProfile: "किसान प्रोफाइल",
    dealerProducts: "डीलर",
    myOrders: "मेरे ऑर्डर",
    voiceAssistant: "आवाज़ सहायक",

    scanCrop: "फसल स्कैन करें",
    localDealers: "स्थानीय डीलर",
    buyProducts: "सामान खरीदें",
    checkMandi: "मंडी भाव देखें",
    trackPurchase: "खरीद की स्थिति देखें",
    farmingServices: "कृषि सेवाएं",

    back: "वापस",
    refresh: "रीफ्रेश",
    loading: "लोड हो रहा है...",
    save: "सेव करें",
    cancel: "रद्द करें",
    continue: "जारी रखें",
    retry: "फिर प्रयास करें",

    languageChanged: "भाषा सफलतापूर्वक बदल दी गई है।",
    noInformation: "जानकारी उपलब्ध नहीं है।",
    openingAgriSaathi: "एग्रीसाथी खुल रहा है...",
    latestOrder: "नवीनतम ऑर्डर",
    farmProduct: "कृषि उत्पाद",
    quantity: "मात्रा",
    trackOrder: "ऑर्डर देखें",
    schemes: "योजनाएं",
    nearbyServices: "नजदीकी कृषि सेवाएं",
    nearbyServicesDescription: "नजदीकी कृषि कार्यालय, मिट्टी जांच केंद्र, उपकरण सेवाएं और अन्य किसान सहायता खोजें।",
    openNearbyServices: "नजदीकी सेवाएं खोलें",
    voice: "आवाज़",
    waitingForDealer: "डीलर की प्रतीक्षा",
    dealerAccepted: "डीलर ने स्वीकार किया",
    orderRejected: "ऑर्डर अस्वीकार हुआ",
    markedDelivered: "डिलीवर बताया गया",
    deliveryConfirmed: "डिलीवरी की पुष्टि",
    paymentConfirmed: "भुगतान की पुष्टि",
    completed: "पूरा हुआ",
    cancelled: "रद्द हुआ",
    orderUpdate: "ऑर्डर अपडेट",
    appLanguage: "ऐप की भाषा",
    changeLanguageAnytime: "किसान मॉड्यूल की भाषा कभी भी बदलें।",
    languageUpdated: "ऐप की भाषा बदल दी गई।",
    myProfile: "मेरी प्रोफाइल",
    personalFarmInformation: "व्यक्तिगत और खेती की जानकारी।",    goodMorning: "सुप्रभात",
    goodAfternoon: "शुभ दोपहर",
    goodEvening: "शुभ संध्या",
    farmer: "किसान",
    farmLocationNotAdded: "खेत का स्थान नहीं जोड़ा गया",
    openNotifications: "सूचनाएं खोलें",
    loadingLocalWeather: "स्थानीय मौसम लोड हो रहा है...",
    currentWeather: "वर्तमान मौसम",
    humidity: "नमी",
    weatherUnavailable: "मौसम उपलब्ध नहीं है",
    allowLocationForWeather: "स्थानीय मौसम के लिए स्थान अनुमति दें।",
    openVoiceAssistant: "एग्रीसाथी वॉइस सहायक खोलें",
    askAgriSaathi: "एग्रीसाथी से पूछें",
    speakInYourLanguage: "माइक्रोफोन दबाकर अपनी भाषा में बोलें।",
    startSpeaking: "बोलना शुरू करें",
    checkDisease: "रोग जांचें",
    prices: "भाव",
    whatDoYouNeed: "आपको क्या चाहिए?",
    loadingMarketPrice: "फसल बाजार भाव लोड हो रहा है...",
    marketPrice: "बाजार भाव",
    cropPrices: "फसल के भाव",
    noCurrentMarketRecord: "वर्तमान भाव नहीं मिला। सभी फसलें और मंडियां देखने के लिए बाजार पेज खोलें।",
    viewMarketPrices: "बाजार भाव देखें",
    localMarketPrice: "स्थानीय बाजार भाव",
    localMandi: "स्थानीय मंडी",
    nearbyMarket: "नजदीकी बाजार",
    perQuintal: "प्रति क्विंटल",
    minimum: "न्यूनतम",
    maximum: "अधिकतम",
    compareAllMarkets: "सभी बाजारों की तुलना करें",

  },

  ta: {
    selectLanguage: "மொழியைத் தேர்ந்தெடுக்கவும்",
    chooseLanguage: "உங்களுக்கு விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்",
    smartFarmingCompanion: "ஸ்மார்ட் விவசாய துணை",
    welcomeFarmer: "விவசாயிக்கு வரவேற்பு",
    chooseService: "கீழே ஒரு சேவையைத் தேர்ந்தெடுக்கவும்",

    login: "உள்நுழை",
    logout: "வெளியேறு",
    createAccount: "கணக்கு உருவாக்கு",
    email: "மின்னஞ்சல்",
    password: "கடவுச்சொல்",
    dashboard: "முகப்புப் பலகை",

    home: "முகப்பு",
    orders: "ஆர்டர்கள்",
    notifications: "அறிவிப்புகள்",
    community: "சமூகம்",
    profile: "சுயவிவரம்",
    settings: "அமைப்புகள்",

    weather: "வானிலை",
    cropDisease: "பயிர் நோய்",
    marketPrices: "சந்தை விலை",
    govtSchemes: "அரசு திட்டங்கள்",
    farmerProfile: "விவசாயி சுயவிவரம்",
    dealerProducts: "விற்பனையாளர்கள்",
    myOrders: "என் ஆர்டர்கள்",
    voiceAssistant: "குரல் உதவியாளர்",

    scanCrop: "பயிரை ஸ்கேன் செய்க",
    localDealers: "உள்ளூர் விற்பனையாளர்கள்",
    buyProducts: "பொருட்கள் வாங்குக",
    checkMandi: "சந்தை விலையைப் பார்க்கவும்",
    trackPurchase: "வாங்கியதை கண்காணிக்கவும்",
    farmingServices: "விவசாய சேவைகள்",

    back: "பின்செல்",
    refresh: "புதுப்பிக்கவும்",
    loading: "ஏற்றுகிறது...",
    save: "சேமிக்கவும்",
    cancel: "ரத்து செய்க",
    continue: "தொடரவும்",
    retry: "மீண்டும் முயற்சிக்கவும்",

    languageChanged: "மொழி வெற்றிகரமாக மாற்றப்பட்டது.",
    noInformation: "தகவல் கிடைக்கவில்லை.",
  },

  kn: {
    selectLanguage: "ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ",
    chooseLanguage: "ನಿಮ್ಮ ಇಷ್ಟದ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    smartFarmingCompanion: "ಸ್ಮಾರ್ಟ್ ಕೃಷಿ ಸಂಗಾತಿ",
    welcomeFarmer: "ಸ್ವಾಗತ ರೈತರೇ",
    chooseService: "ಕೆಳಗಿನ ಸೇವೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",

    login: "ಲಾಗಿನ್",
    logout: "ಲಾಗೌಟ್",
    createAccount: "ಖಾತೆ ರಚಿಸಿ",
    email: "ಇಮೇಲ್",
    password: "ಪಾಸ್‌ವರ್ಡ್",
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",

    home: "ಮುಖಪುಟ",
    orders: "ಆರ್ಡರ್‌ಗಳು",
    notifications: "ಸೂಚನೆಗಳು",
    community: "ಸಮುದಾಯ",
    profile: "ಪ್ರೊಫೈಲ್",
    settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",

    weather: "ಹವಾಮಾನ",
    cropDisease: "ಬೆಳೆ ರೋಗ",
    marketPrices: "ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳು",
    govtSchemes: "ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು",
    farmerProfile: "ರೈತ ಪ್ರೊಫೈಲ್",
    dealerProducts: "ಡೀಲರ್‌ಗಳು",
    myOrders: "ನನ್ನ ಆರ್ಡರ್‌ಗಳು",
    voiceAssistant: "ಧ್ವನಿ ಸಹಾಯಕ",

    scanCrop: "ಬೆಳೆ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
    localDealers: "ಸ್ಥಳೀಯ ಡೀಲರ್‌ಗಳು",
    buyProducts: "ಉತ್ಪನ್ನ ಖರೀದಿಸಿ",
    checkMandi: "ಮಾರುಕಟ್ಟೆ ಬೆಲೆ ನೋಡಿ",
    trackPurchase: "ಖರೀದಿ ಸ್ಥಿತಿ ನೋಡಿ",
    farmingServices: "ಕೃಷಿ ಸೇವೆಗಳು",

    back: "ಹಿಂದೆ",
    refresh: "ರಿಫ್ರೆಶ್",
    loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    save: "ಉಳಿಸಿ",
    cancel: "ರದ್ದುಮಾಡಿ",
    continue: "ಮುಂದುವರಿಸಿ",
    retry: "ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ",

    languageChanged: "ಭಾಷೆಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಬದಲಾಯಿಸಲಾಗಿದೆ.",
    noInformation: "ಮಾಹಿತಿ ಲಭ್ಯವಿಲ್ಲ.",
  },

  ml: {
    selectLanguage: "ഭാഷ തിരഞ്ഞെടുക്കുക",
    chooseLanguage: "നിങ്ങളുടെ ഇഷ്ടഭാഷ തിരഞ്ഞെടുക്കുക",
    smartFarmingCompanion: "സ്മാർട്ട് കൃഷി കൂട്ടായി",
    welcomeFarmer: "കർഷകനു സ്വാഗതം",
    chooseService: "താഴെ ഒരു സേവനം തിരഞ്ഞെടുക്കുക",

    login: "ലോഗിൻ",
    logout: "ലോഗൗട്ട്",
    createAccount: "അക്കൗണ്ട് സൃഷ്ടിക്കുക",
    email: "ഇമെയിൽ",
    password: "പാസ്‌വേഡ്",
    dashboard: "ഡാഷ്ബോർഡ്",

    home: "ഹോം",
    orders: "ഓർഡറുകൾ",
    notifications: "അറിയിപ്പുകൾ",
    community: "സമൂഹം",
    profile: "പ്രൊഫൈൽ",
    settings: "ക്രമീകരണങ്ങൾ",

    weather: "കാലാവസ്ഥ",
    cropDisease: "വിള രോഗം",
    marketPrices: "മാർക്കറ്റ് വിലകൾ",
    govtSchemes: "സർക്കാർ പദ്ധതികൾ",
    farmerProfile: "കർഷക പ്രൊഫൈൽ",
    dealerProducts: "ഡീലർമാർ",
    myOrders: "എന്റെ ഓർഡറുകൾ",
    voiceAssistant: "വോയ്സ് അസിസ്റ്റന്റ്",

    scanCrop: "വിള സ്കാൻ ചെയ്യുക",
    localDealers: "പ്രാദേശിക ഡീലർമാർ",
    buyProducts: "ഉൽപ്പന്നങ്ങൾ വാങ്ങുക",
    checkMandi: "മാർക്കറ്റ് വില പരിശോധിക്കുക",
    trackPurchase: "വാങ്ങൽ നില പരിശോധിക്കുക",
    farmingServices: "കൃഷി സേവനങ്ങൾ",

    back: "പിന്നോട്ട്",
    refresh: "പുതുക്കുക",
    loading: "ലോഡ് ചെയ്യുന്നു...",
    save: "സേവ് ചെയ്യുക",
    cancel: "റദ്ദാക്കുക",
    continue: "തുടരുക",
    retry: "വീണ്ടും ശ്രമിക്കുക",

    languageChanged: "ഭാഷ വിജയകരമായി മാറ്റി.",
    noInformation: "വിവരം ലഭ്യമല്ല.",
  },

  mr: {
    selectLanguage: "भाषा निवडा",
    chooseLanguage: "आपली पसंतीची भाषा निवडा",
    smartFarmingCompanion: "स्मार्ट शेती साथी",
    welcomeFarmer: "शेतकरी मित्रा, स्वागत आहे",
    chooseService: "खालील सेवा निवडा",

    login: "लॉगिन",
    logout: "लॉगआउट",
    createAccount: "खाते तयार करा",
    email: "ईमेल",
    password: "पासवर्ड",
    dashboard: "डॅशबोर्ड",

    home: "मुख्यपृष्ठ",
    orders: "ऑर्डर",
    notifications: "सूचना",
    community: "समुदाय",
    profile: "प्रोफाइल",
    settings: "सेटिंग्ज",

    weather: "हवामान",
    cropDisease: "पीक रोग",
    marketPrices: "बाजार भाव",
    govtSchemes: "सरकारी योजना",
    farmerProfile: "शेतकरी प्रोफाइल",
    dealerProducts: "विक्रेते",
    myOrders: "माझे ऑर्डर",
    voiceAssistant: "आवाज सहाय्यक",

    scanCrop: "पीक स्कॅन करा",
    localDealers: "स्थानिक विक्रेते",
    buyProducts: "उत्पादने खरेदी करा",
    checkMandi: "बाजार भाव पहा",
    trackPurchase: "खरेदीची स्थिती पहा",
    farmingServices: "शेती सेवा",

    back: "मागे",
    refresh: "रीफ्रेश",
    loading: "लोड होत आहे...",
    save: "सेव्ह करा",
    cancel: "रद्द करा",
    continue: "पुढे जा",
    retry: "पुन्हा प्रयत्न करा",

    languageChanged: "भाषा यशस्वीपणे बदलली.",
    noInformation: "माहिती उपलब्ध नाही.",
  },

  bn: {
    selectLanguage: "ভাষা নির্বাচন করুন",
    chooseLanguage: "আপনার পছন্দের ভাষা নির্বাচন করুন",
    smartFarmingCompanion: "স্মার্ট কৃষি সহায়ক",
    welcomeFarmer: "কৃষককে স্বাগতম",
    chooseService: "নিচের একটি পরিষেবা নির্বাচন করুন",

    login: "লগইন",
    logout: "লগআউট",
    createAccount: "অ্যাকাউন্ট তৈরি করুন",
    email: "ইমেল",
    password: "পাসওয়ার্ড",
    dashboard: "ড্যাশবোর্ড",

    home: "হোম",
    orders: "অর্ডার",
    notifications: "বিজ্ঞপ্তি",
    community: "সম্প্রদায়",
    profile: "প্রোফাইল",
    settings: "সেটিংস",

    weather: "আবহাওয়া",
    cropDisease: "ফসলের রোগ",
    marketPrices: "বাজার দর",
    govtSchemes: "সরকারি প্রকল্প",
    farmerProfile: "কৃষক প্রোফাইল",
    dealerProducts: "ডিলার",
    myOrders: "আমার অর্ডার",
    voiceAssistant: "ভয়েস সহায়ক",

    scanCrop: "ফসল স্ক্যান করুন",
    localDealers: "স্থানীয় ডিলার",
    buyProducts: "পণ্য কিনুন",
    checkMandi: "বাজার দর দেখুন",
    trackPurchase: "ক্রয় অনুসরণ করুন",
    farmingServices: "কৃষি পরিষেবা",

    back: "পিছনে",
    refresh: "রিফ্রেশ",
    loading: "লোড হচ্ছে...",
    save: "সংরক্ষণ করুন",
    cancel: "বাতিল করুন",
    continue: "চালিয়ে যান",
    retry: "আবার চেষ্টা করুন",

    languageChanged: "ভাষা সফলভাবে পরিবর্তিত হয়েছে।",
    noInformation: "তথ্য পাওয়া যায়নি।",
  },

  gu: {
    selectLanguage: "ભાષા પસંદ કરો",
    chooseLanguage: "તમારી પસંદગીની ભાષા પસંદ કરો",
    smartFarmingCompanion: "સ્માર્ટ ખેતી સાથી",
    welcomeFarmer: "ખેડૂતનું સ્વાગત છે",
    chooseService: "નીચેની સેવા પસંદ કરો",

    login: "લોગિન",
    logout: "લોગઆઉટ",
    createAccount: "ખાતું બનાવો",
    email: "ઇમેઇલ",
    password: "પાસવર્ડ",
    dashboard: "ડેશબોર્ડ",

    home: "હોમ",
    orders: "ઓર્ડર",
    notifications: "સૂચનાઓ",
    community: "સમુદાય",
    profile: "પ્રોફાઇલ",
    settings: "સેટિંગ્સ",

    weather: "હવામાન",
    cropDisease: "પાક રોગ",
    marketPrices: "બજાર ભાવ",
    govtSchemes: "સરકારી યોજનાઓ",
    farmerProfile: "ખેડૂત પ્રોફાઇલ",
    dealerProducts: "ડીલર",
    myOrders: "મારા ઓર્ડર",
    voiceAssistant: "વોઇસ સહાયક",

    scanCrop: "પાક સ્કેન કરો",
    localDealers: "સ્થાનિક ડીલર",
    buyProducts: "ઉત્પાદનો ખરીદો",
    checkMandi: "બજાર ભાવ જુઓ",
    trackPurchase: "ખરીદી તપાસો",
    farmingServices: "ખેતી સેવાઓ",

    back: "પાછળ",
    refresh: "રિફ્રેશ",
    loading: "લોડ થઈ રહ્યું છે...",
    save: "સાચવો",
    cancel: "રદ કરો",
    continue: "ચાલુ રાખો",
    retry: "ફરી પ્રયાસ કરો",

    languageChanged: "ભાષા સફળતાપૂર્વક બદલાઈ.",
    noInformation: "માહિતી ઉપલબ્ધ નથી.",
  },

  pa: {
    selectLanguage: "ਭਾਸ਼ਾ ਚੁਣੋ",
    chooseLanguage: "ਆਪਣੀ ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ ਚੁਣੋ",
    smartFarmingCompanion: "ਸਮਾਰਟ ਖੇਤੀ ਸਾਥੀ",
    welcomeFarmer: "ਕਿਸਾਨ ਜੀ ਦਾ ਸੁਆਗਤ ਹੈ",
    chooseService: "ਹੇਠਾਂ ਇੱਕ ਸੇਵਾ ਚੁਣੋ",

    login: "ਲਾਗਇਨ",
    logout: "ਲਾਗਆਉਟ",
    createAccount: "ਖਾਤਾ ਬਣਾਓ",
    email: "ਈਮੇਲ",
    password: "ਪਾਸਵਰਡ",
    dashboard: "ਡੈਸ਼ਬੋਰਡ",

    home: "ਮੁੱਖ ਪੰਨਾ",
    orders: "ਆਰਡਰ",
    notifications: "ਸੂਚਨਾਵਾਂ",
    community: "ਭਾਈਚਾਰਾ",
    profile: "ਪ੍ਰੋਫਾਈਲ",
    settings: "ਸੈਟਿੰਗਜ਼",

    weather: "ਮੌਸਮ",
    cropDisease: "ਫਸਲ ਰੋਗ",
    marketPrices: "ਮਾਰਕੀਟ ਭਾਅ",
    govtSchemes: "ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ",
    farmerProfile: "ਕਿਸਾਨ ਪ੍ਰੋਫਾਈਲ",
    dealerProducts: "ਡੀਲਰ",
    myOrders: "ਮੇਰੇ ਆਰਡਰ",
    voiceAssistant: "ਆਵਾਜ਼ ਸਹਾਇਕ",

    scanCrop: "ਫਸਲ ਸਕੈਨ ਕਰੋ",
    localDealers: "ਸਥਾਨਕ ਡੀਲਰ",
    buyProducts: "ਸਮਾਨ ਖਰੀਦੋ",
    checkMandi: "ਮੰਡੀ ਭਾਅ ਵੇਖੋ",
    trackPurchase: "ਖਰੀਦ ਦੀ ਸਥਿਤੀ ਵੇਖੋ",
    farmingServices: "ਖੇਤੀ ਸੇਵਾਵਾਂ",

    back: "ਪਿੱਛੇ",
    refresh: "ਰਿਫਰੈਸ਼",
    loading: "ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...",
    save: "ਸੇਵ ਕਰੋ",
    cancel: "ਰੱਦ ਕਰੋ",
    continue: "ਜਾਰੀ ਰੱਖੋ",
    retry: "ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ",

    languageChanged: "ਭਾਸ਼ਾ ਸਫਲਤਾਪੂਰਵਕ ਬਦਲੀ ਗਈ।",
    noInformation: "ਜਾਣਕਾਰੀ ਉਪਲਬਧ ਨਹੀਂ ਹੈ।",
  },

  ur: {
    selectLanguage: "زبان منتخب کریں",
    chooseLanguage: "اپنی پسندیدہ زبان منتخب کریں",
    smartFarmingCompanion: "اسمارٹ فارمنگ ساتھی",
    welcomeFarmer: "کسان صاحب خوش آمدید",
    chooseService: "نیچے سے ایک خدمت منتخب کریں",

    login: "لاگ اِن",
    logout: "لاگ آؤٹ",
    createAccount: "اکاؤنٹ بنائیں",
    email: "ای میل",
    password: "پاس ورڈ",
    dashboard: "ڈیش بورڈ",

    home: "ہوم",
    orders: "آرڈرز",
    notifications: "اطلاعات",
    community: "برادری",
    profile: "پروفائل",
    settings: "سیٹنگز",

    weather: "موسم",
    cropDisease: "فصل کی بیماری",
    marketPrices: "بازار قیمتیں",
    govtSchemes: "سرکاری اسکیمیں",
    farmerProfile: "کسان پروفائل",
    dealerProducts: "ڈیلر",
    myOrders: "میرے آرڈرز",
    voiceAssistant: "آواز معاون",

    scanCrop: "فصل اسکین کریں",
    localDealers: "قریبی ڈیلر",
    buyProducts: "سامان خریدیں",
    checkMandi: "منڈی قیمت دیکھیں",
    trackPurchase: "خریداری کی حالت دیکھیں",
    farmingServices: "زرعی خدمات",

    back: "واپس",
    refresh: "تازہ کریں",
    loading: "لوڈ ہو رہا ہے...",
    save: "محفوظ کریں",
    cancel: "منسوخ کریں",
    continue: "جاری رکھیں",
    retry: "دوبارہ کوشش کریں",

    languageChanged: "زبان کامیابی سے تبدیل ہوگئی۔",
    noInformation: "معلومات دستیاب نہیں ہیں۔",
  },

  or: {
    selectLanguage: "ଭାଷା ବାଛନ୍ତୁ",
    chooseLanguage: "ଆପଣଙ୍କ ପସନ୍ଦର ଭାଷା ବାଛନ୍ତୁ",
    smartFarmingCompanion: "ସ୍ମାର୍ଟ କୃଷି ସାଥୀ",
    welcomeFarmer: "କୃଷକଙ୍କୁ ସ୍ୱାଗତ",
    chooseService: "ନିମ୍ନରୁ ଏକ ସେବା ବାଛନ୍ତୁ",

    login: "ଲଗଇନ",
    logout: "ଲଗଆଉଟ",
    createAccount: "ଖାତା ସୃଷ୍ଟି କରନ୍ତୁ",
    email: "ଇମେଲ",
    password: "ପାସୱାର୍ଡ",
    dashboard: "ଡ୍ୟାଶବୋର୍ଡ",

    home: "ହୋମ",
    orders: "ଅର୍ଡର",
    notifications: "ସୂଚନା",
    community: "ସମୁଦାୟ",
    profile: "ପ୍ରୋଫାଇଲ",
    settings: "ସେଟିଂସ",

    weather: "ଆବହାଓଆ",
    cropDisease: "ଫସଲ ରୋଗ",
    marketPrices: "ବଜାର ଦର",
    govtSchemes: "ସରକାରୀ ଯୋଜନା",
    farmerProfile: "କୃଷକ ପ୍ରୋଫାଇଲ",
    dealerProducts: "ଡିଲର",
    myOrders: "ମୋ ଅର୍ଡର",
    voiceAssistant: "ଭଏସ୍ ସହାୟକ",

    scanCrop: "ଫସଲ ସ୍କାନ କରନ୍ତୁ",
    localDealers: "ସ୍ଥାନୀୟ ଡିଲର",
    buyProducts: "ସାମଗ୍ରୀ କିଣନ୍ତୁ",
    checkMandi: "ବଜାର ଦର ଦେଖନ୍ତୁ",
    trackPurchase: "କ୍ରୟ ସ୍ଥିତି ଦେଖନ୍ତୁ",
    farmingServices: "କୃଷି ସେବା",

    back: "ପଛକୁ",
    refresh: "ରିଫ୍ରେଶ",
    loading: "ଲୋଡ୍ ହେଉଛି...",
    save: "ସେଭ୍ କରନ୍ତୁ",
    cancel: "ବାତିଲ କରନ୍ତୁ",
    continue: "ଆଗକୁ ବଢ଼ନ୍ତୁ",
    retry: "ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ",

    languageChanged: "ଭାଷା ସଫଳତାର ସହିତ ବଦଳିଗଲା।",
    noInformation: "ସୂଚନା ଉପଲବ୍ଧ ନାହିଁ।",
  },
};

function isBrowser() {
  return typeof window !== "undefined";
}

export function isSupportedLanguage(code) {
  return languages.some((language) => language.code === code);
}

export function normalizeLanguage(code) {
  const normalized = String(code || "")
    .trim()
    .toLowerCase()
    .split("-")[0];

  return isSupportedLanguage(normalized)
    ? normalized
    : DEFAULT_LANGUAGE;
}

export function getLanguage() {
  if (!isBrowser()) {
    return DEFAULT_LANGUAGE;
  }

  const savedLanguage = window.localStorage.getItem(
    LANGUAGE_STORAGE_KEY
  );

  if (savedLanguage) {
    return normalizeLanguage(savedLanguage);
  }

  return normalizeLanguage(
    window.navigator.language || DEFAULT_LANGUAGE
  );
}

export function getLanguageDetails(code = getLanguage()) {
  const normalizedCode = normalizeLanguage(code);

  return (
    languages.find(
      (language) => language.code === normalizedCode
    ) || languages[0]
  );
}

export function getLanguageName(code = getLanguage()) {
  return getLanguageDetails(code).nativeName;
}

export function getSpeechLocale(code = getLanguage()) {
  return getLanguageDetails(code).locale;
}

export function getLanguageDirection(code = getLanguage()) {
  return getLanguageDetails(code).direction;
}

export function applyLanguageToDocument(code = getLanguage()) {
  if (!isBrowser() || !document?.documentElement) {
    return;
  }

  const details = getLanguageDetails(code);

  document.documentElement.lang = details.locale;
  document.documentElement.dir = details.direction;
}

export function setLanguage(code) {
  const normalizedCode = normalizeLanguage(code);

  if (!isBrowser()) {
    return normalizedCode;
  }

  window.localStorage.setItem(
    LANGUAGE_STORAGE_KEY,
    normalizedCode
  );

  applyLanguageToDocument(normalizedCode);

  window.dispatchEvent(
    new CustomEvent(LANGUAGE_CHANGE_EVENT, {
      detail: {
        language: normalizedCode,
      },
    })
  );

  return normalizedCode;
}

export function subscribeLanguageChange(callback) {
  if (!isBrowser() || typeof callback !== "function") {
    return () => {};
  }

  function handleLanguageChange(event) {
    callback(
      normalizeLanguage(
        event?.detail?.language || getLanguage()
      )
    );
  }

  window.addEventListener(
    LANGUAGE_CHANGE_EVENT,
    handleLanguageChange
  );

  return () => {
    window.removeEventListener(
      LANGUAGE_CHANGE_EVENT,
      handleLanguageChange
    );
  };
}

function replaceVariables(text, variables = {}) {
  return Object.entries(variables).reduce(
    (result, [key, value]) =>
      result.replaceAll(`{{${key}}}`, String(value)),
    String(text)
  );
}

export function t(
  key,
  variables = {},
  languageCode = getLanguage()
) {
  const language = normalizeLanguage(languageCode);

  const translatedValue =
    translations[language]?.[key] ??
    translations[DEFAULT_LANGUAGE]?.[key];

  if (translatedValue === undefined) {
    return key;
  }

  if (typeof translatedValue !== "string") {
    return translatedValue;
  }

  return replaceVariables(translatedValue, variables);
}

export function createTranslator(languageCode) {
  const language = normalizeLanguage(languageCode);

  return (key, variables = {}) =>
    t(key, variables, language);
}

export function initializeLanguage() {
  const language = getLanguage();

  applyLanguageToDocument(language);

  return language;
}

export function getLanguageStorageKey() {
  return LANGUAGE_STORAGE_KEY;
}
