export const languages = [
  { code: "en", name: "English" },
  { code: "te", name: "తెలుగు" },
  { code: "hi", name: "हिन्दी" },
  { code: "ta", name: "தமிழ்" },
  { code: "kn", name: "ಕನ್ನಡ" },
  { code: "ml", name: "മലയാളം" },
  { code: "mr", name: "मराठी" },
  { code: "bn", name: "বাংলা" },
  { code: "gu", name: "ગુજરાતી" },
  { code: "pa", name: "ਪੰਜਾਬੀ" },
  { code: "ur", name: "اردو" },
  { code: "or", name: "ଓଡ଼ିଆ" },
];

export const translations = {
  en: {
    selectLanguage: "Select Language",
    chooseLanguage: "Choose your preferred language",
    smartFarmingCompanion: "Smart Farming Companion",
    welcomeFarmer: "Welcome Farmer",
    chooseService: "Choose a service below",
    login: "Login",
    createAccount: "Create account",
    email: "Email",
    password: "Password",
    dashboard: "Dashboard",
    weather: "Weather",
    cropDisease: "Crop Disease",
    irrigationAdvice: "Irrigation Advice",
    animalCare: "Animal Care",
    marketPrices: "Market Prices",
    govtSchemes: "Government Schemes",
    farmerProfile: "Farmer Profile",
    settings: "Settings",
  },
  te: {
    selectLanguage: "భాషను ఎంచుకోండి",
    chooseLanguage: "మీకు ఇష్టమైన భాషను ఎంచుకోండి",
    smartFarmingCompanion: "స్మార్ట్ వ్యవసాయ సహాయకుడు",
    welcomeFarmer: "స్వాగతం రైతు",
    chooseService: "క్రింది సేవను ఎంచుకోండి",
    login: "లాగిన్",
    createAccount: "ఖాతా సృష్టించండి",
    email: "ఇమెయిల్",
    password: "పాస్‌వర్డ్",
    dashboard: "డాష్‌బోర్డ్",
    weather: "వాతావరణం",
    cropDisease: "పంట వ్యాధి",
    irrigationAdvice: "నీటిపారుదల సలహా",
    animalCare: "పశు సంరక్షణ",
    marketPrices: "మార్కెట్ ధరలు",
    govtSchemes: "ప్రభుత్వ పథకాలు",
    farmerProfile: "రైతు ప్రొఫైల్",
    settings: "సెట్టింగ్స్",
  },
  hi: {
    selectLanguage: "भाषा चुनें",
    chooseLanguage: "अपनी पसंदीदा भाषा चुनें",
    smartFarmingCompanion: "स्मार्ट खेती साथी",
    welcomeFarmer: "स्वागत है किसान",
    chooseService: "नीचे एक सेवा चुनें",
    login: "लॉगिन",
    createAccount: "खाता बनाएं",
    email: "ईमेल",
    password: "पासवर्ड",
    dashboard: "डैशबोर्ड",
    weather: "मौसम",
    cropDisease: "फसल रोग",
    irrigationAdvice: "सिंचाई सलाह",
    animalCare: "पशु देखभाल",
    marketPrices: "बाजार भाव",
    govtSchemes: "सरकारी योजनाएं",
    farmerProfile: "किसान प्रोफाइल",
    settings: "सेटिंग्स",
  },
  ta: {
    selectLanguage: "மொழியைத் தேர்ந்தெடுக்கவும்",
    chooseLanguage: "உங்களுக்கு விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்",
    smartFarmingCompanion: "ஸ்மார்ட் விவசாய துணை",
    welcomeFarmer: "வரவேற்கிறோம் விவசாயி",
    chooseService: "கீழே ஒரு சேவையைத் தேர்ந்தெடுக்கவும்",
    login: "உள்நுழை",
    createAccount: "கணக்கு உருவாக்கு",
    email: "மின்னஞ்சல்",
    password: "கடவுச்சொல்",
    dashboard: "டாஷ்போர்டு",
    weather: "வானிலை",
    cropDisease: "பயிர் நோய்",
    irrigationAdvice: "பாசன ஆலோசனை",
    animalCare: "கால்நடை பராமரிப்பு",
    marketPrices: "சந்தை விலை",
    govtSchemes: "அரசு திட்டங்கள்",
    farmerProfile: "விவசாயி சுயவிவரம்",
    settings: "அமைப்புகள்",
  },
  kn: {
    selectLanguage: "ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ",
    chooseLanguage: "ನಿಮ್ಮ ಇಷ್ಟದ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    smartFarmingCompanion: "ಸ್ಮಾರ್ಟ್ ಕೃಷಿ ಸಂಗಾತಿ",
    welcomeFarmer: "ಸ್ವಾಗತ ರೈತರೆ",
    chooseService: "ಕೆಳಗಿನ ಸೇವೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    login: "ಲಾಗಿನ್",
    createAccount: "ಖಾತೆ ರಚಿಸಿ",
    email: "ಇಮೇಲ್",
    password: "ಪಾಸ್‌ವರ್ಡ್",
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    weather: "ಹವಾಮಾನ",
    cropDisease: "ಬೆಳೆ ರೋಗ",
    irrigationAdvice: "ನೀರಾವರಿ ಸಲಹೆ",
    animalCare: "ಪಶು ಆರೈಕೆ",
    marketPrices: "ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳು",
    govtSchemes: "ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು",
    farmerProfile: "ರೈತ ಪ್ರೊಫೈಲ್",
    settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
  },
  ml: {
    selectLanguage: "ഭാഷ തിരഞ്ഞെടുക്കുക",
    chooseLanguage: "നിങ്ങളുടെ ഇഷ്ടഭാഷ തിരഞ്ഞെടുക്കുക",
    smartFarmingCompanion: "സ്മാർട്ട് കൃഷി കൂട്ടായി",
    welcomeFarmer: "സ്വാഗതം കർഷകാ",
    chooseService: "താഴെ ഒരു സേവനം തിരഞ്ഞെടുക്കുക",
    login: "ലോഗിൻ",
    createAccount: "അക്കൗണ്ട് സൃഷ്ടിക്കുക",
    email: "ഇമെയിൽ",
    password: "പാസ്‌വേഡ്",
    dashboard: "ഡാഷ്ബോർഡ്",
    weather: "കാലാവസ്ഥ",
    cropDisease: "വിള രോഗം",
    irrigationAdvice: "ജലസേചന ഉപദേശം",
    animalCare: "മൃഗ പരിപാലനം",
    marketPrices: "മാർക്കറ്റ് വിലകൾ",
    govtSchemes: "സർക്കാർ പദ്ധതികൾ",
    farmerProfile: "കർഷക പ്രൊഫൈൽ",
    settings: "ക്രമീകരണങ്ങൾ",
  },
  mr: {
    selectLanguage: "भाषा निवडा",
    chooseLanguage: "आपली पसंतीची भाषा निवडा",
    smartFarmingCompanion: "स्मार्ट शेती साथी",
    welcomeFarmer: "स्वागत आहे शेतकरी",
    chooseService: "खालील सेवा निवडा",
    login: "लॉगिन",
    createAccount: "खाते तयार करा",
    email: "ईमेल",
    password: "पासवर्ड",
    dashboard: "डॅशबोर्ड",
    weather: "हवामान",
    cropDisease: "पीक रोग",
    irrigationAdvice: "सिंचन सल्ला",
    animalCare: "पशुपालन काळजी",
    marketPrices: "बाजार भाव",
    govtSchemes: "सरकारी योजना",
    farmerProfile: "शेतकरी प्रोफाइल",
    settings: "सेटिंग्ज",
  },
  bn: {
    selectLanguage: "ভাষা নির্বাচন করুন",
    chooseLanguage: "আপনার পছন্দের ভাষা নির্বাচন করুন",
    smartFarmingCompanion: "স্মার্ট কৃষি সহায়ক",
    welcomeFarmer: "স্বাগতম কৃষক",
    chooseService: "নিচের একটি পরিষেবা নির্বাচন করুন",
    login: "লগইন",
    createAccount: "অ্যাকাউন্ট তৈরি করুন",
    email: "ইমেল",
    password: "পাসওয়ার্ড",
    dashboard: "ড্যাশবোর্ড",
    weather: "আবহাওয়া",
    cropDisease: "ফসলের রোগ",
    irrigationAdvice: "সেচ পরামর্শ",
    animalCare: "পশু যত্ন",
    marketPrices: "বাজার দর",
    govtSchemes: "সরকারি প্রকল্প",
    farmerProfile: "কৃষক প্রোফাইল",
    settings: "সেটিংস",
  },
  gu: {
    selectLanguage: "ભાષા પસંદ કરો",
    chooseLanguage: "તમારી પસંદગીની ભાષા પસંદ કરો",
    smartFarmingCompanion: "સ્માર્ટ ખેતી સાથી",
    welcomeFarmer: "સ્વાગત છે ખેડૂત",
    chooseService: "નીચેની સેવા પસંદ કરો",
    login: "લોગિન",
    createAccount: "ખાતું બનાવો",
    email: "ઇમેઇલ",
    password: "પાસવર્ડ",
    dashboard: "ડેશબોર્ડ",
    weather: "હવામાન",
    cropDisease: "પાક રોગ",
    irrigationAdvice: "સિંચાઈ સલાહ",
    animalCare: "પશુ સંભાળ",
    marketPrices: "બજાર ભાવ",
    govtSchemes: "સરકારી યોજનાઓ",
    farmerProfile: "ખેડૂત પ્રોફાઇલ",
    settings: "સેટિંગ્સ",
  },
  pa: {
    selectLanguage: "ਭਾਸ਼ਾ ਚੁਣੋ",
    chooseLanguage: "ਆਪਣੀ ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ ਚੁਣੋ",
    smartFarmingCompanion: "ਸਮਾਰਟ ਖੇਤੀ ਸਾਥੀ",
    welcomeFarmer: "ਜੀ ਆਇਆਂ ਨੂੰ ਕਿਸਾਨ",
    chooseService: "ਹੇਠਾਂ ਇੱਕ ਸੇਵਾ ਚੁਣੋ",
    login: "ਲਾਗਇਨ",
    createAccount: "ਖਾਤਾ ਬਣਾਓ",
    email: "ਈਮੇਲ",
    password: "ਪਾਸਵਰਡ",
    dashboard: "ਡੈਸ਼ਬੋਰਡ",
    weather: "ਮੌਸਮ",
    cropDisease: "ਫਸਲ ਰੋਗ",
    irrigationAdvice: "ਸਿੰਚਾਈ ਸਲਾਹ",
    animalCare: "ਪਸ਼ੂ ਸੰਭਾਲ",
    marketPrices: "ਮਾਰਕੀਟ ਭਾਅ",
    govtSchemes: "ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ",
    farmerProfile: "ਕਿਸਾਨ ਪ੍ਰੋਫਾਈਲ",
    settings: "ਸੈਟਿੰਗਜ਼",
  },
  ur: {
    selectLanguage: "زبان منتخب کریں",
    chooseLanguage: "اپنی پسندیدہ زبان منتخب کریں",
    smartFarmingCompanion: "اسمارٹ فارمنگ ساتھی",
    welcomeFarmer: "خوش آمدید کسان",
    chooseService: "نیچے سے ایک خدمت منتخب کریں",
    login: "لاگ اِن",
    createAccount: "اکاؤنٹ بنائیں",
    email: "ای میل",
    password: "پاس ورڈ",
    dashboard: "ڈیش بورڈ",
    weather: "موسم",
    cropDisease: "فصل کی بیماری",
    irrigationAdvice: "آبپاشی مشورہ",
    animalCare: "جانوروں کی دیکھ بھال",
    marketPrices: "بازار قیمتیں",
    govtSchemes: "سرکاری اسکیمیں",
    farmerProfile: "کسان پروفائل",
    settings: "سیٹنگز",
  },
  or: {
    selectLanguage: "ଭାଷା ବାଛନ୍ତୁ",
    chooseLanguage: "ଆପଣଙ୍କ ପସନ୍ଦର ଭାଷା ବାଛନ୍ତୁ",
    smartFarmingCompanion: "ସ୍ମାର୍ଟ କୃଷି ସାଥୀ",
    welcomeFarmer: "ସ୍ୱାଗତ କୃଷକ",
    chooseService: "ନିମ୍ନରୁ ଏକ ସେବା ବାଛନ୍ତୁ",
    login: "ଲଗଇନ",
    createAccount: "ଖାତା ସୃଷ୍ଟି କରନ୍ତୁ",
    email: "ଇମେଲ",
    password: "ପାସୱାର୍ଡ",
    dashboard: "ଡ୍ୟାଶବୋର୍ଡ",
    weather: "ଆବହାଓଆ",
    cropDisease: "ଫସଲ ରୋଗ",
    irrigationAdvice: "ସିଚାଇ ପରାମର୍ଶ",
    animalCare: "ପଶୁ ଯତ୍ନ",
    marketPrices: "ବଜାର ଦର",
    govtSchemes: "ସରକାରୀ ଯୋଜନା",
    farmerProfile: "କୃଷକ ପ୍ରୋଫାଇଲ",
    settings: "ସେଟିଂସ",
  },
};

export function getLanguage() {
  return localStorage.getItem("agrisathi-language") || "en";
}

export function setLanguage(code) {
  localStorage.setItem("agrisathi-language", code);
}

export function t(key) {
  const lang = getLanguage();
  return translations[lang]?.[key] || translations.en[key] || key;
}